<a href="https://colab.research.google.com/github/raju1207/Car_Sales_Analysis/blob/main/Car_Sales_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Car_sales.csv')
df

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,CL,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Volvo,V40,3.545,NaN,Passenger,24.40,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
153,Volvo,S70,15.245,NaN,Passenger,27.50,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
154,Volvo,V70,17.531,NaN,Passenger,28.80,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
155,Volvo,C70,3.493,NaN,Passenger,45.50,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
156,Volvo,S80,18.969,NaN,Passenger,36.00,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

In [3]:
df.iloc[4]

Manufacturer                Audi
Model                         A4
Sales_in_thousands        20.397
__year_resale_value       22.255
Vehicle_type           Passenger
Price_in_thousands         23.99
Engine_size                  1.8
Horsepower                 150.0
Wheelbase                  102.6
Width                       68.2
Length                     178.0
Curb_weight                2.998
Fuel_capacity               16.4
Fuel_efficiency             27.0
Latest_Launch          10/8/2011
Power_perf_factor      62.777639
Name: 4, dtype: object

In [4]:
df.iloc[3:6]

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
5,Audi,A6,18.780,23.555,Passenger,33.95,2.8,200.0,108.7,76.1,192.0,3.561,18.5,22.0,8/9/2011,84.565105

In [5]:
df.iloc[3:40]

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
3,Acura,RL,8.588,29.725,Passenger,42.000,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.990,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
5,Audi,A6,18.780,23.555,Passenger,33.950,2.8,200.0,108.7,76.1,192.0,3.561,18.5,22.0,8/9/2011,84.565105
6,Audi,A8,1.380,39.000,Passenger,62.000,4.2,310.0,113.0,74.0,198.2,3.902,23.7,21.0,2/27/2012,134.656858
7,BMW,323i,19.747,NaN,Passenger,26.990,2.5,170.0,107.3,68.4,176.0,3.179,16.6,26.0,6/28/2011,71.191207
8,BMW,328i,9.231,28.675,Passenger,33.400,2.8,193.0,107.3,68.5,176.0,3.197,16.6,24.0,1/29/2012,81.877069
9,BMW,528i,17.527,36.125,Passenger,38.900,2.8,193.0,111.4,70.9,188.0,3.472,18.5,25.0,4/4/2011,83.998724
10,Buick,Century,91.561,12.475,Passenger,21.975,3.1,175.0,109.0,72.7,194.6,3.368,17.5,25.0,11/2/2011,71.181451
11,Buick,Regal,39.350,13.740,Passenger,25.300,3.8,240.0,109.0,72.7,196.2,3.543,17.5,23.0,9/3/2011,95.636703
12,Buick,Park Avenue,27.851,20.190,Passenger,31.965,3.8,205.0,113.8,74.7,206.8,3.778,18.5,24.0,3/23/2012,85.828408
13,Buick,LeSabre,83.257,13.360,Passenger,27.885,3.8,205.0,112.2,73.5,200.0,3.591,17.5,25.0,7/23/2011,84.254526
14,Cadillac,DeVille,63.729,22.525,Passenger,39.895,4.6,275.0,115.3,74.5,207.2,3.978,18.5,22.0,2/23/2012,113.854598
15,Cadillac,Seville,15.943,27.100,Passenger,44.475,4.6,275.0,112.2,75.0,201.0,NaN,18.5,22.0,4/29/2011,115.621358
16,Cadillac,Eldorado,6.536,25.725,Passenger,39.665,4.6,275.0,108.0,75.5,200.6,3.843,19.0,22.0,11/27/2011,113.765874
17,Cadillac,Catera,11.185,18.225,Passenger,31.010,3.0,200.0,107.4,70.3,194.8,3.770,18.0,22.0,9/28/2011,83.483094
18,Cadillac,Escalade,14.785,NaN,Car,46.225,5.7,255.0,117.5,77.0,201.2,5.572,30.0,15.0,4/17/2012,109.509117
19,Chevrolet,Cavalier,145.519,9.250,Passenger,13.260,2.2,115.0,104.1,67.9,180.9,2.676,14.3,27.0,8/17/2011,46.363347
20,Chevrolet,Malibu,135.126,11.225,Passenger,16.535,3.1,170.0,107.0,69.4,190.4,3.051,15.0,25.0,3/19/2012,67.314462
21,Chevrolet,Lumina,24.629,10.310,Passenger,18.890,3.1,175.0,107.5,72.5,200.9,3.330,16.6,25.0,5/24/2011,69.991396
22,Chevrolet,Monte Carlo,42.593,11.525,Passenger,19.390,3.4,180.0,110.5,72.7,197.9,3.340,17.0,27.0,12/22/2011,72.030917
23,Chevrolet,Camaro,26.402,13.025,Passenger,24.340,3.8,200.0,101.1,74.1,193.2,3.500,16.8,25.0,10/23/2011,81.118543
24,Chevrolet,Corvette,17.947,36.225,Passenger,45.705,5.7,345.0,104.5,73.6,179.7,3.210,19.1,22.0,5/12/2012,141.141150
25,Chevrolet,Prizm,32.299,9.125,Passenger,13.960,1.8,120.0,97.1,66.7,174.3,2.398,13.2,33.0,9/11/2011,48.297636
26,Chevrolet,Metro,21.855,5.160,Passenger,9.235,1.0,55.0,93.1,62.6,149.4,1.895,10.3,45.0,4/13/2012,23.276272
27,Chevrolet,Impala,107.995,NaN,Passenger,18.890,3.4,180.0,110.5,73.0,200.0,3.389,17.0,27.0,6/18/2011,71.838039
28,Chrysler,Sebring Coupe,7.854,12.360,Passenger,19.840,2.5,163.0,103.7,69.7,190.9,2.967,15.9,24.0,1/16/2012,65.957184
29,Chrysler,Sebring Conv.,32.775,14.180,Passenger,24.495,2.5,168.0,106.0,69.2,193.0,3.332,16.0,24.0,11/17/2011,69.521355
30,Chrysler,Concorde,31.148,13.725,Passenger,22.245,2.7,200.0,113.0,74.4,209.1,3.452,17.0,26.0,6/6/2012,80.023782
31,Chrysler,Cirrus,32.306,12.640,Passenger,16.480,2.0,132.0,108.0,71.0,186.0,2.911,16.0,27.0,10/6/2011,53.566200
32,Chrysler,LHS,13.462,17.325,Passenger,28.340,3.5,253.0,113.0,74.4,207.7,3.564,17.0,23.0,5/8/2012,101.329281
33,Chrysler,Town & Country,53.480,19.540,Car,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7/13/2011,NaN
34,Chrysler,300M,30.696,NaN,Passenger,29.185,3.5,253.0,113.0,74.4,197.8,3.567,17.0,23.0,2/10/2012,101.655244
35,Dodge,Neon,76.034,7.750,Passenger,12.640,2.0,132.0,105.0,74.4,174.4,2.567,12.5,29.0,12/12/2011,52.084899
36,Dodge,Avenger,4.734,12.545,Passenger,19.045,2.5,163.0,103.7,69.1,190.2,2.879,15.9,24.0,7/1/2012,65.650508
37,Dodge,Stratus,71.186,10.185,Passenger,20.230,2.5,168.0,108.0,71.0,186.0,3.058,16.0,24.0,10/31/2011,67.876108
38,Dodge,Intrepid,88.028,12.275,Passenger,22.505,2.7,202.0,113.0,74.7,203.7,3.489,17.0,NaN,6/2/2012,80.831470
39,Dodge,Viper,0.916,58.470,Passenger,69.725,8.0,450.0,96.2,75.7,176.7,3.375,19.0,16.0,8/7/2011,188.144323

In [6]:
df.iloc[3:76,5:14]

,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency
3,42.000,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0
4,23.990,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0
5,33.950,2.8,200.0,108.7,76.1,192.0,3.561,18.5,22.0
6,62.000,4.2,310.0,113.0,74.0,198.2,3.902,23.7,21.0
7,26.990,2.5,170.0,107.3,68.4,176.0,3.179,16.6,26.0
...,...,...,...,...,...,...,...,...,...
71,37.805,3.0,225.0,110.2,70.9,189.2,3.638,19.8,23.0
72,46.305,4.0,300.0,110.2,70.9,189.2,3.693,19.8,21.0
73,54.005,4.0,290.0,112.2,72.0,196.7,3.890,22.5,22.0
74,60.105,4.7,230.0,112.2,76.4,192.5,5.401,25.4,15.0
75,34.605,3.0,220.0,103.0,71.5,180.1,3.900,17.2,21.0

In [7]:
df.iloc[[20,34,55,66,89,9],[3,5,9,8]]

    __year_resale_value  Price_in_thousands  Width  Wheelbase
20               11.225              16.535   69.4      107.0
34                  NaN              29.185   74.4      113.0
55                7.850              12.050   69.4      117.5
66                  NaN              42.800   71.6      114.5
89               14.875              22.605   78.2      114.7
9                36.125              38.900   70.9      111.4

In [8]:
df.iloc[:,7]

0      140.0
1      225.0
2      225.0
3      210.0
4      150.0
       ...
152    160.0
153    168.0
154    168.0
155    236.0
156    201.0
Name: Horsepower, Length: 157, dtype: float64

In [9]:
df.columns

Index(['Manufacturer', 'Model', 'Sales_in_thousands', '__year_resale_value',
       'Vehicle_type', 'Price_in_thousands', 'Engine_size', 'Horsepower',
       'Wheelbase', 'Width', 'Length', 'Curb_weight', 'Fuel_capacity',
       'Fuel_efficiency', 'Latest_Launch', 'Power_perf_factor'],
      dtype='object')

In [10]:
df.loc[3:7,['Width', 'Length']]

   Width  Length
3   71.4   196.6
4   68.2   178.0
5   76.1   192.0
6   74.0   198.2
7   68.4   176.0

In [11]:
df

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,CL,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Volvo,V40,3.545,NaN,Passenger,24.40,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
153,Volvo,S70,15.245,NaN,Passenger,27.50,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
154,Volvo,V70,17.531,NaN,Passenger,28.80,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
155,Volvo,C70,3.493,NaN,Passenger,45.50,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
156,Volvo,S80,18.969,NaN,Passenger,36.00,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

In [12]:
df.set_index("Model")

,Manufacturer,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
Model,,,,,,,,,,,,,,,
Integra,Acura,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
TL,Acura,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
CL,Acura,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
RL,Acura,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
A4,Audi,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
V40,Volvo,3.545,NaN,Passenger,24.40,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
S70,Volvo,15.245,NaN,Passenger,27.50,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
V70,Volvo,17.531,NaN,Passenger,28.80,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
C70,Volvo,3.493,NaN,Passenger,45.50,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
S80,Volvo,18.969,NaN,Passenger,36.00,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

In [13]:
df.set_index("Model",inplace=True)  #dont run 2 times
df

,Manufacturer,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
Model,,,,,,,,,,,,,,,
Integra,Acura,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
TL,Acura,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
CL,Acura,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
RL,Acura,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
A4,Audi,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
V40,Volvo,3.545,NaN,Passenger,24.40,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
S70,Volvo,15.245,NaN,Passenger,27.50,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
V70,Volvo,17.531,NaN,Passenger,28.80,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
C70,Volvo,3.493,NaN,Passenger,45.50,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
S80,Volvo,18.969,NaN,Passenger,36.00,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

In [14]:
df.loc["S70":"C70"]

,Manufacturer,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
Model,,,,,,,,,,,,,,,
S70,Volvo,15.245,NaN,Passenger,27.5,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
V70,Volvo,17.531,NaN,Passenger,28.8,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
C70,Volvo,3.493,NaN,Passenger,45.5,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357

In [15]:
df.iloc[-4:-1]

,Manufacturer,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
Model,,,,,,,,,,,,,,,
S70,Volvo,15.245,NaN,Passenger,27.5,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
V70,Volvo,17.531,NaN,Passenger,28.8,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
C70,Volvo,3.493,NaN,Passenger,45.5,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 157 entries, Integra to S80
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Manufacturer         157 non-null    object
 1   Sales_in_thousands   157 non-null    float64
 2   __year_resale_value  121 non-null    float64
 3   Vehicle_type         157 non-null    object
 4   Price_in_thousands   155 non-null    float64
 5   Engine_size          156 non-null    float64
 6   Horsepower           156 non-null    float64
 7   Wheelbase            156 non-null    float64
 8   Width                156 non-null    float64
 9   Length               156 non-null    float64
 10  Curb_weight          155 non-null    float64
 11  Fuel_capacity        156 non-null    float64
 12  Fuel_efficiency      154 non-null    float64
 13  Latest_Launch        157 non-null    object
 14  Power_perf_factor    155 non-null    float64
dtypes: float64(12), object(3)
memory usage: 23.7+ KB

In [17]:
df.describe()

,Sales_in_thousands,__year_resale_value,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Power_perf_factor
count,157.000000,121.000000,155.000000,156.000000,156.000000,156.000000,156.000000,156.000000,155.000000,156.000000,154.000000,155.000000
mean,52.998076,18.072975,27.390755,3.060897,185.948718,107.487179,71.150000,187.343590,3.378026,17.951923,23.844156,77.043591
std,68.029422,11.453384,14.351653,1.044653,56.700321,7.641303,3.451872,13.431754,0.630502,3.887921,4.282706,25.142664
min,0.110000,5.160000,9.235000,1.000000,55.000000,92.600000,62.600000,149.400000,1.895000,10.300000,15.000000,23.276272
25%,14.114000,11.260000,18.017500,2.300000,149.500000,103.000000,68.400000,177.575000,2.971000,15.800000,21.000000,60.407707
50%,29.450000,14.180000,22.799000,3.000000,177.500000,107.000000,70.550000,187.900000,3.342000,17.200000,24.000000,72.030917
75%,67.956000,19.875000,31.947500,3.575000,215.000000,112.200000,73.425000,196.125000,3.799500,19.575000,26.000000,89.414878
max,540.561000,67.550000,85.500000,8.000000,450.000000,138.700000,79.900000,224.500000,5.572000,32.000000,45.000000,188.144323

In [18]:
df.describe(include="all")

,Manufacturer,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
count,157,157.000000,121.000000,157,155.000000,156.000000,156.000000,156.000000,156.000000,156.000000,155.000000,156.000000,154.000000,157,155.000000
unique,30,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,130,NaN
top,Dodge,NaN,NaN,Passenger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10/5/2012,NaN
freq,11,NaN,NaN,116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN
mean,NaN,52.998076,18.072975,NaN,27.390755,3.060897,185.948718,107.487179,71.150000,187.343590,3.378026,17.951923,23.844156,NaN,77.043591
std,NaN,68.029422,11.453384,NaN,14.351653,1.044653,56.700321,7.641303,3.451872,13.431754,0.630502,3.887921,4.282706,NaN,25.142664
min,NaN,0.110000,5.160000,NaN,9.235000,1.000000,55.000000,92.600000,62.600000,149.400000,1.895000,10.300000,15.000000,NaN,23.276272
25%,NaN,14.114000,11.260000,NaN,18.017500,2.300000,149.500000,103.000000,68.400000,177.575000,2.971000,15.800000,21.000000,NaN,60.407707
50%,NaN,29.450000,14.180000,NaN,22.799000,3.000000,177.500000,107.000000,70.550000,187.900000,3.342000,17.200000,24.000000,NaN,72.030917
75%,NaN,67.956000,19.875000,NaN,31.947500,3.575000,215.000000,112.200000,73.425000,196.125000,3.799500,19.575000,26.000000,NaN,89.414878
max,NaN,540.561000,67.550000,NaN,85.500000,8.000000,450.000000,138.700000,79.900000,224.500000,5.572000,32.000000,45.000000,NaN,188.144323

In [19]:
df["Manufacturer"].unique()

array(['Acura', 'Audi', 'BMW', 'Buick', 'Cadillac', 'Chevrolet',
       'Chrysler', 'Dodge', 'Ford', 'Honda', 'Hyundai', 'Infiniti',
       'Jaguar', 'Jeep', 'Lexus', 'Lincoln', 'Mitsubishi', 'Mercury',
       'Mercedes-B', 'Nissan', 'Oldsmobile', 'Plymouth', 'Pontiac',
       'Porsche', 'Saab', 'Saturn', 'Subaru', 'Toyota', 'Volkswagen',
       'Volvo'], dtype=object)

In [20]:
df["Manufacturer"].nunique()

30

In [21]:
df.Manufacturer.unique()

array(['Acura', 'Audi', 'BMW', 'Buick', 'Cadillac', 'Chevrolet',
       'Chrysler', 'Dodge', 'Ford', 'Honda', 'Hyundai', 'Infiniti',
       'Jaguar', 'Jeep', 'Lexus', 'Lincoln', 'Mitsubishi', 'Mercury',
       'Mercedes-B', 'Nissan', 'Oldsmobile', 'Plymouth', 'Pontiac',
       'Porsche', 'Saab', 'Saturn', 'Subaru', 'Toyota', 'Volkswagen',
       'Volvo'], dtype=object)

In [22]:
df.shape

(157, 15)

In [23]:
pd.set_option("display.max_rows",None)

In [24]:
df

,Manufacturer,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
Model,,,,,,,,,,,,,,,
Integra,Acura,16.919,16.360,Passenger,21.500,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
TL,Acura,39.384,19.875,Passenger,28.400,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
CL,Acura,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
RL,Acura,8.588,29.725,Passenger,42.000,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
A4,Audi,20.397,22.255,Passenger,23.990,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
A6,Audi,18.780,23.555,Passenger,33.950,2.8,200.0,108.7,76.1,192.0,3.561,18.5,22.0,8/9/2011,84.565105
A8,Audi,1.380,39.000,Passenger,62.000,4.2,310.0,113.0,74.0,198.2,3.902,23.7,21.0,2/27/2012,134.656858
323i,BMW,19.747,NaN,Passenger,26.990,2.5,170.0,107.3,68.4,176.0,3.179,16.6,26.0,6/28/2011,71.191207
328i,BMW,9.231,28.675,Passenger,33.400,2.8,193.0,107.3,68.5,176.0,3.197,16.6,24.0,1/29/2012,81.877069
528i,BMW,17.527,36.125,Passenger,38.900,2.8,193.0,111.4,70.9,188.0,3.472,18.5,25.0,4/4/2011,83.998724
Century,Buick,91.561,12.475,Passenger,21.975,3.1,175.0,109.0,72.7,194.6,3.368,17.5,25.0,11/2/2011,71.181451
Regal,Buick,39.350,13.740,Passenger,25.300,3.8,240.0,109.0,72.7,196.2,3.543,17.5,23.0,9/3/2011,95.636703
Park Avenue,Buick,27.851,20.190,Passenger,31.965,3.8,205.0,113.8,74.7,206.8,3.778,18.5,24.0,3/23/2012,85.828408
LeSabre,Buick,83.257,13.360,Passenger,27.885,3.8,205.0,112.2,73.5,200.0,3.591,17.5,25.0,7/23/2011,84.254526
DeVille,Cadillac,63.729,22.525,Passenger,39.895,4.6,275.0,115.3,74.5,207.2,3.978,18.5,22.0,2/23/2012,113.854598
Seville,Cadillac,15.943,27.100,Passenger,44.475,4.6,275.0,112.2,75.0,201.0,NaN,18.5,22.0,4/29/2011,115.621358
Eldorado,Cadillac,6.536,25.725,Passenger,39.665,4.6,275.0,108.0,75.5,200.6,3.843,19.0,22.0,11/27/2011,113.765874
Catera,Cadillac,11.185,18.225,Passenger,31.010,3.0,200.0,107.4,70.3,194.8,3.770,18.0,22.0,9/28/2011,83.483094
Escalade,Cadillac,14.785,NaN,Car,46.225,5.7,255.0,117.5,77.0,201.2,5.572,30.0,15.0,4/17/2012,109.509117
Cavalier,Chevrolet,145.519,9.250,Passenger,13.260,2.2,115.0,104.1,67.9,180.9,2.676,14.3,27.0,8/17/2011,46.363347
Malibu,Chevrolet,135.126,11.225,Passenger,16.535,3.1,170.0,107.0,69.4,190.4,3.051,15.0,25.0,3/19/2012,67.314462
Lumina,Chevrolet,24.629,10.310,Passenger,18.890,3.1,175.0,107.5,72.5,200.9,3.330,16.6,25.0,5/24/2011,69.991396
Monte Carlo,Chevrolet,42.593,11.525,Passenger,19.390,3.4,180.0,110.5,72.7,197.9,3.340,17.0,27.0,12/22/2011,72.030917
Camaro,Chevrolet,26.402,13.025,Passenger,24.340,3.8,200.0,101.1,74.1,193.2,3.500,16.8,25.0,10/23/2011,81.118543
Corvette,Chevrolet,17.947,36.225,Passenger,45.705,5.7,345.0,104.5,73.6,179.7,3.210,19.1,22.0,5/12/2012,141.141150
Prizm,Chevrolet,32.299,9.125,Passenger,13.960,1.8,120.0,97.1,66.7,174.3,2.398,13.2,33.0,9/11/2011,48.297636
Metro,Chevrolet,21.855,5.160,Passenger,9.235,1.0,55.0,93.1,62.6,149.4,1.895,10.3,45.0,4/13/2012,23.276272
Impala,Chevrolet,107.995,NaN,Passenger,18.890,3.4,180.0,110.5,73.0,200.0,3.389,17.0,27.0,6/18/2011,71.838039
Sebring Coupe,Chrysler,7.854,12.360,Passenger,19.840,2.5,163.0,103.7,69.7,190.9,2.967,15.9,24.0,1/16/2012,65.957184
Sebring Conv.,Chrysler,32.775,14.180,Passenger,24.495,2.5,168.0,106.0,69.2,193.0,3.332,16.0,24.0,11/17/2011,69.521355
Concorde,Chrysler,31.148,13.725,Passenger,22.245,2.7,200.0,113.0,74.4,209.1,3.452,17.0,26.0,6/6/2012,80.023782
Cirrus,Chrysler,32.306,12.640,Passenger,16.480,2.0,132.0,108.0,71.0,186.0,2.911,16.0,27.0,10/6/2011,53.566200
LHS,Chrysler,13.462,17.325,Passenger,28.340,3.5,253.0,113.0,74.4,207.7,3.564,17.0,23.0,5/8/2012,101.329281
Town & Country,Chrysler,53.480,19.540,Car,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7/13/2011,NaN
300M,Chrysler,30.696,NaN,Passenger,29.185,3.5,253.0,113.0,74.4,197.8,3.567,17.0,23.0,2/10/2012,101.655244
Neon,Dodge,76.034,7.750,Passenger,12.640,2.0,132.0,105.0,74.4,174.4,2.567,12.5,29.0,12/12/2011,52.084899
Avenger,Dodge,4.734,12.545,Passenger,19.045,2.5,163.0,103.7,69.1,190.2,2.879,15.9,24.0,7/1/2012,65.650508
Stratus,Dodge,71.186,10.185,Passenger,20.230,2.5,168.0,108.0,71.0,186.0,3.058,16.0,24.0,10/31/2011,67.876108
Intrepid,Dodge,88.028,12.275,Passenger,22.505,2.7,202.0,113.0,74.7,203.7,3.489,17.0,NaN,6/2/2012,80.831470
Viper,Dodge,0.916,58.470,Passenger,69.725,8.0,450.0,96.2,75.7,176.7,3.375,19.0,16.0,8/7/2011,188.144323
Ram Pickup,Dodge,227.061,15.060,Car,19.460,5.2,230.0,138.7,79.3,224.2,4.470,26.0,17.0,3/6/2012,90.211700
Ram Wagon,Dodge,16.767,15.510,Car,21.315,3.9,175.0,109.6,78.8,192.6,4.245,32.0,15.0,1/6/2012,71.135292
Ram Van,Dodge,31.038,13.425,Car,18.575,3.9,175.0,127.2,78.8,208.5,4.298,32.0,16.0,7/26/2012,70.078322
Dakota,Dodge,111.313,11.260,Car,16.980,2.5,120.0,131.0,71.5,215.0,3.557,22.0,19.0,11/25/2011,49.645002
Durango,Dodge,101.323,NaN,Car,26.310,5.2,230.0,115.7,71.7,193.5,4.394,25.0,17.0,6/27/2012,92.854125
Caravan,Dodge,181.749,12.025,Car,19.565,2.4,150.0,113.3,76.8,186.3,3.533,20.0,24.0,9/1/2011,61.227000
Escort,Ford,70.227,7.425,Passenger,12.070,2.0,110.0,98.4,67.0,174.7,2.468,12.7,30.0,3/31/2012,44.083709
Mustang,Ford,113.369,12.760,Passenger,21.560,3.8,190.0,101.3,73.1,183.2,3.203,15.7,24.0,1/31/2012,76.509185
Contour,Ford,35.068,8.835,Passenger,17.035,2.5,170.0,106.5,69.1,184.6,2.769,15.0,25.0,8/20/2012,67.351011
Taurus,Ford,245.815,10.055,Passenger,17.885,3.0,155.0,108.5,73.0,197.6,3.368,16.0,24.0,12/20/2011,62.503740
Focus,Ford,175.670,NaN,Passenger,12.315,2.0,107.0,103.0,66.9,174.8,2.564,13.2,30.0,7/22/2012,43.117132
Crown Victoria,Ford,63.403,14.210,Passenger,22.195,4.6,200.0,114.7,78.2,212.0,3.908,19.0,21.0,9/26/2011,80.499537
Explorer,Ford,276.747,16.640,Car,31.930,4.0,210.0,111.6,70.2,190.7,3.876,21.0,19.0,4/25/2012,87.635496
Windstar,Ford,155.787,13.175,Car,21.410,3.0,150.0,120.7,76.6,200.9,3.761,26.0,21.0,2/25/2012,62.095048
Expedition,Ford,125.338,23.575,Car,36.135,4.6,240.0,119.0,78.7,204.6,4.808,26.0,16.0,9/14/2012,100.024802
Ranger,Ford,220.650,7.850,Car,12.050,2.5,119.0,117.5,69.4,200.7,3.086,20.0,23.0,1/14/2012,47.389531
F-Series,Ford,540.561,15.075,Car,26.935,4.6,220.0,138.5,79.1,224.5,4.241,25.1,18.0,8/16/2012,89.401935
Civic,Honda,199.685,9.850,Passenger,12.885,1.6,106.0,103.2,67.1,175.1,2.339,11.9,32.0,10/21/2011,42.879097
Accord,Honda,230.902,13.210,Passenger,15.350,2.3,135.0,106.9,70.3,188.8,2.932,17.1,27.0,5/20/2012,54.269548
CR-V,Honda,73.203,17.710,Car,20.550,2.0,146.0,103.2,68.9,177.6,3.219,15.3,24.0,3/21/2012,60.087967
Passport,Honda,12.855,17.525,Car,26.600,3.2,205.0,106.4,70.4,178.2,3.857,21.1,19.0,10/9/2012,83.602501
Odyssey,Honda,76.029,19.490,Car,26.000,3.5,210.0,118.1,75.6,201.2,4.288,20.0,23.0,2/8/2012,85.217691
Accent,Hyundai,41.184,5.860,Passenger,9.699,1.5,92.0,96.1,65.7,166.7,2.240,11.9,31.0,9/10/2012,36.672284
Elantra,Hyundai,66.692,7.825,Passenger,11.799,2.0,140.0,100.4,66.9,174.0,2.626,14.5,27.0,11/15/2011,54.590045
Sonata,Hyundai,29.450,8.910,Passenger,14.999,2.4,148.0,106.3,71.6,185.4,3.072,17.2,25.0,6/14/2012,58.758249
I30,Infiniti,23.713,19.690,Passenger,29.465,3.0,227.0,108.3,70.2,193.7,3.342,18.5,25.0,4/15/2012,92.436889
S-Type,Jaguar,15.467,NaN,Passenger,42.800,3.0,240.0,114.5,71.6,191.3,3.650,18.4,21.0,11/3/2012,102.178985
Wrangler,Jeep,55.557,13.475,Car,14.460,2.5,120.0,93.4,66.7,152.0,3.045,19.0,17.0,3/4/2012,48.672898
Cherokee,Jeep,80.556,13.775,Car,21.620,4.0,190.0,101.4,69.4,167.5,3.194,20.0,20.0,10/5/2012,76.584440
Grand Cherokee,Jeep,157.040,18.810,Car,26.895,4.0,195.0,105.9,72.3,181.5,3.880,20.5,19.0,12/10/2011,80.387779
ES300,Lexus,24.072,26.975,Passenger,31.505,3.0,210.0,105.1,70.5,190.2,3.373,18.5,23.0,7/9/2012,87.211001
GS300,Lexus,12.698,32.075,Passenger,37.805,3.0,225.0,110.2,70.9,189.2,3.638,19.8,23.0,5/10/2012,94.946698
GS400,Lexus,3.334,NaN,Passenger,46.305,4.0,300.0,110.2,70.9,189.2,3.693,19.8,21.0,11/28/2012,125.013357
LS400,Lexus,6.375,40.375,Passenger,54.005,4.0,290.0,112.2,72.0,196.7,3.890,22.5,22.0,3/29/2012,124.446716
LX470,Lexus,9.126,NaN,Car,60.105,4.7,230.0,112.2,76.4,192.5,5.401,25.4,15.0,10/30/2012,105.760458
RX300,Lexus,51.238,NaN,Car,34.605,3.0,220.0,103.0,71.5,180.1,3.900,17.2,21.0,1/4/2012,91.943802
Continental,Lincoln,13.798,20.525,Passenger,39.080,4.6,275.0,109.0,73.6,208.5,3.868,20.0,22.0,8/3/2012,113.540207
Town car,Lincoln,48.911,21.725,Passenger,43.330,4.6,215.0,117.7,78.2,215.3,4.121,19.0,21.0,6/4/2012,93.957917
Navigator,Lincoln,22.925,NaN,Car,42.660,5.4,300.0,119.0,79.9,204.8,5.393,30.0,15.0,12/23/2012,123.972047
Mirage,Mitsubishi,26.232,8.325,Passenger,13.987,1.8,113.0,98.4,66.5,173.6,2.250,13.2,30.0,4/23/2012,45.832181
Eclipse,Mitsubishi,42.541,10.395,Passenger,19.047,2.4,154.0,100.8,68.9,175.4,2.910,15.9,24.0,11/24/2012,62.441962
Galant,Mitsubishi,55.616,10.595,Passenger,17.357,2.4,145.0,103.7,68.5,187.8,2.945,16.3,25.0,1/29/2012,58.606773
Diamante,Mitsubishi,5.711,16.575,Passenger,24.997,3.5,210.0,107.1,70.3,194.1,3.443,19.0,22.0,8/28/2012,84.830779
3000GT,Mitsubishi,0.110,20.940,Passenger,25.450,3.0,161.0,97.2,72.4,180.3,3.131,19.8,21.0,6/29/2012,67.544155
Montero,Mitsubishi,11.337,19.125,Car,31.807,3.5,200.0,107.3,69.9,186.6,4.520,24.3,18.0,1/17/2012,83.920815
Montero Sport,Mitsubishi,39.348,13.880,Car,22.527,3.0,173.0,107.3,66.7,178.3,3.510,19.5,20.0,5/18/2012,70.660942
Mystique,Mercury,14.351,8.800,Passenger,16.240,2.0,125.0,106.5,69.1,184.8,2.769,15.0,28.0,12/19/2012,50.997748
Cougar,Mercury,26.529,13.890,Passenger,16.540,2.0,125.0,106.4,69.6,185.0,2.892,16.0,30.0,2/23/2012,51.113474
Sable,Mercury,67.956,11.030,Passenger,19.035,3.0,153.0,108.5,73.0,199.7,3.379,16.0,24.0,9/22/2012,62.239967
Grand Marquis,Mercury,81.174,14.875,Passenger,22.605,4.6,200.0,114.7,78.2,212.0,3.958,19.0,21.0,7/24/2012,80.657696
Mountaineer,Mercury,27.609,20.430,Car,27.560,4.0,210.0,111.6,70.2,190.1,3.876,21.0,18.0,2/13/2008,85.949744
Villager,Mercury,20.380,14.795,Car,22.510,3.3,170.0,112.2,74.9,194.7,3.944,20.0,21.0,10/20/2009,69.671461
C-Class,Mercedes-B,18.392,26.050,Passenger,31.750,2.3,185.0,105.9,67.7,177.4,3.250,16.4,26.0,4/24/2011,78.280731
E-Class,Mercedes-B,27.602,41.450,Passenger,49.900,3.2,221.0,111.5,70.8,189.4,3.823,21.1,25.0,7/12/2011,98.249737
S-Class,Mercedes-B,16.774,50.375,Passenger,69.700,4.3,275.0,121.5,73.1,203.1,4.133,23.2,21.0,6/13/2011,125.273876
SL-Class,Mercedes-B,3.311,58.600,Passenger,82.600,5.0,302.0,99.0,71.3,177.1,4.125,21.1,20.0,3/17/2011,139.982294
SLK,Mercedes-B,7.998,NaN,Passenger,38.900,2.3,190.0,94.5,67.5,157.9,3.055,15.9,26.0,1/16/2011,82.807362
SLK230,Mercedes-B,1.526,NaN,Passenger,41.000,2.3,185.0,94.5,67.5,157.3,2.975,14.0,27.0,8/6/2011,81.848969
CLK Coupe,Mercedes-B,11.592,NaN,Passenger,41.600,3.2,215.0,105.9,67.8,180.3,3.213,16.4,26.0,7/8/2011,92.925792
CL500,Mercedes-B,0.954,NaN,Passenger,85.500,5.0,302.0,113.6,73.1,196.6,4.115,23.2,20.0,4/11/2011,141.100985
M-Class,Mercedes-B,28.976,NaN,Car,35.300,3.2,215.0,111.0,72.2,180.6,4.387,19.0,20.0,2/10/2011,90.495532
Sentra,Nissan,42.643,8.450,Passenger,13.499,1.8,126.0,99.8,67.3,177.5,2.593,13.2,30.0,8/31/2011,50.241978
Altima,Nissan,88.094,11.295,Passenger,20.390,2.4,155.0,103.1,69.1,183.5,3.012,15.9,25.0,8/2/2011,63.313728
Maxima,Nissan,79.853,15.125,Passenger,26.249,3.0,222.0,108.3,70.3,190.5,3.294,18.5,25.0,5/6/2011,89.427820
Quest,Nissan,27.308,15.380,Car,26.399,3.3,170.0,112.2,74.9,194.8,3.991,20.0,21.0,3/7/2011,71.171664
Pathfinder,Nissan,42.574,17.810,Car,29.299,3.3,170.0,106.3,71.7,182.6,3.947,21.0,19.0,9/25/2011,72.290355
Xterra,Nissan,54.158,NaN,Car,22.799,3.3,170.0,104.3,70.4,178.0,3.821,19.4,18.0,1/24/2011,69.782944
Frontier,Nissan,65.005,NaN,Car,17.890,3.3,170.0,116.1,66.5,196.1,3.217,19.4,18.0,8/27/2011,67.889271
Cutlass,Oldsmobile,1.112,11.240,Passenger,18.145,3.1,150.0,107.0,69.4,192.0,3.102,15.2,25.0,5/31/2011,60.861612
Intrigue,Oldsmobile,38.554,NaN,Passenger,24.150,3.5,215.0,109.0,73.6,195.9,3.455,18.0,NaN,4/1/2011,86.272523
Alero,Oldsmobile,80.255,NaN,Passenger,18.270,2.4,150.0,107.0,70.1,186.7,2.958,15.0,27.0,10/20/2009,60.727447
Aurora,Oldsmobile,14.690,19.890,Passenger,36.229,4.0,250.0,113.8,74.4,205.4,3.967,18.5,22.0,2/18/2011,103.441693
Bravada,Oldsmobile,20.017,19.925,Car,31.598,4.3,190.0,107.0,67.8,181.2,4.068,17.5,19.0,9/21/2011,80.511673
Silhouette,Oldsmobile,24.361,15.240,Car,25.345,3.4,185.0,120.0,72.2,201.4,3.948,25.0,22.0,6/25/2011,76.096570
Neon,Plymouth,32.734,7.750,Passenger,12.640,2.0,132.0,105.0,74.4,174.4,2.559,12.5,29.0,4/26/2011,52.084899
Breeze,Plymouth,5.240,9.800,Passenger,16.080,2.0,132.0,108.0,71.0,186.3,2.942,16.0,27.0,11/14/2011,53.411898
Voyager,Plymouth,24.155,12.025,Car,18.850,2.4,150.0,113.3,76.8,186.3,3.528,20.0,24.0,4/24/2011,60.951185
Prowler,Plymouth,1.872,NaN,Passenger,43.000,3.5,253.0,113.3,76.3,165.4,2.850,12.0,21.0,6/27/2012,106.984456
Sunfire,Pontiac,51.645,13.790,Passenger,21.610,2.4,150.0,104.1,68.4,181.9,2.906,15.0,27.0,1/25/2012,62.015870
Grand Am,Pontiac,131.097,10.290,Passenger,19.720,3.4,175.0,107.0,70.4,186.3,3.091,15.2,25.0,11/26/2012,70.389737
Firebird,Pontiac,19.911,17.805,Passenger,25.310,3.8,200.0,101.1,74.5,193.4,3.492,16.8,25.0,6/16/2012,81.492726
Grand Prix,Pontiac,92.364,14.010,Passenger,21.665,3.8,195.0,110.5,72.7,196.5,3.396,18.0,25.0,10/15/2012,78.318168
Bonneville,Pontiac,35.945,13.225,Passenger,23.755,3.8,205.0,112.2,72.6,202.5,3.590,17.5,24.0,5/18/2011,82.661356
Montana,Pontiac,39.572,NaN,Car,25.635,3.4,185.0,120.0,72.7,201.3,3.942,25.0,23.0,7/22/2012,76.208440
Boxter,Porsche,8.982,41.250,Passenger,41.430,2.7,217.0,95.2,70.1,171.0,2.778,17.0,22.0,2/19/2012,93.437331
Carrera Coupe,Porsche,1.280,60.625,Passenger,71.020,3.4,300.0,92.6,69.5,174.5,3.032,17.0,21.0,12/21/2012,134.390975
Carrera Cabrio,Porsche,1.866,67.550,Passenger,74.970,3.4,300.0,92.6,69.5,174.5,3.075,17.0,23.0,7/11/2011,135.914710
5-Sep,Saab,9.191,NaN,Passenger,33.120,2.3,170.0,106.4,70.6,189.2,3.280,18.5,23.0,11/9/2012,73.503778
3-Sep,Saab,12.115,NaN,Passenger,26.100,2.0,185.0,102.6,67.4,182.2,2.990,16.9,23.0,6/12/2011,76.023048
SL,Saturn,80.620,9.200,Passenger,10.685,1.9,100.0,102.4,66.4,176.9,2.332,12.1,33.0,8/16/2012,39.986425
SC,Saturn,24.546,10.590,Passenger,12.535,1.9,100.0,102.4,66.4,180.0,2.367,12.1,33.0,3/16/2011,40.700072
SW,Saturn,5.223,10.790,Passenger,14.290,1.9,124.0,102.4,66.4,176.9,2.452,12.1,31.0,1/15/2011,49.865774
LW,Saturn,8.472,NaN,Passenger,18.835,2.2,137.0,106.5,69.0,190.4,3.075,13.1,27.0,8/5/2011,56.295243
LS,Saturn,49.989,NaN,Passenger,15.010,2.2,137.0,106.5,69.0,190.4,2.910,13.1,28.0,12/4/2012,54.819728
Outback,Subaru,47.107,NaN,Passenger,22.695,2.5,165.0,103.5,67.5,185.8,3.415,16.9,25.0,7/7/2011,67.765908
Forester,Subaru,33.028,NaN,Car,20.095,2.5,165.0,99.4,68.3,175.2,3.125,15.9,24.0,9/10/2012,66.762943
Corolla,Toyota,142.535,10.025,Passenger,13.108,1.8,120.0,97.0,66.7,174.0,2.420,13.2,33.0,4/11/2011,47.968972
Camry,Toyota,247.994,13.245,Passenger,17.518,2.2,133.0,105.2,70.1,188.5,2.998,18.5,27.0,2/10/2011,54.372420
Avalon,Toyota,63.849,18.140,Passenger,25.545,3.0,210.0,107.1,71.7,191.9,3.417,18.5,26.0,8/31/2011,84.911898
Celica,Toyota,33.269,15.445,Passenger,16.875,1.8,140.0,102.4,68.3,170.5,2.425,14.5,31.0,12/29/2012,56.496030
Tacoma,Toyota,84.087,9.575,Car,11.528,2.4,142.0,103.3,66.5,178.7,2.580,15.1,23.0,8/1/2011,55.297117
Sienna,Toyota,65.119,NaN,Car,22.368,3.0,194.0,114.2,73.4,193.5,3.759,20.9,22.0,10/5/2012,78.027219
RAV4,Toyota,25.106,13.325,Car,16.888,2.0,127.0,94.9,66.7,163.8,2.668,15.3,27.0,5/6/2011,51.955109
4Runner,Toyota,68.411,19.425,Car,22.288,2.7,150.0,105.3,66.5,183.3,3.440,18.5,23.0,3/7/2011,62.355577
Land Cruiser,Toyota,9.835,34.080,Car,51.728,4.7,230.0,112.2,76.4,192.5,5.115,25.4,15.0,9/25/2011,102.528984
Golf,Volkswagen,9.761,11.425,Passenger,14.900,2.0,115.0,98.9,68.3,163.3,2.767,14.5,26.0,1/24/2011,46.943877
Jetta,Volkswagen,83.721,13.240,Passenger,16.700,2.0,115.0,98.9,68.3,172.3,2.853,14.5,26.0,8/27/2011,47.638237
Passat,Volkswagen,51.102,16.725,Passenger,21.200,1.8,150.0,106.4,68.5,184.1,3.043,16.4,27.0,10/30/2012,61.701381
Cabrio,Volkswagen,9.569,16.575,Passenger,19.990,2.0,115.0,97.4,66.7,160.4,3.079,13.7,26.0,5/31/2011,48.907372
GTI,Volkswagen,5.596,13.760,Passenger,17.500,2.0,115.0,98.9,68.3,163.3,2.762,14.6,26.0,4/1/2011,47.946841
Beetle,Volkswagen,49.463,NaN,Passenger,15.900,2.0,115.0,98.9,67.9,161.1,2.769,14.5,26.0,10/20/2011,47.329632
S40,Volvo,16.957,NaN,Passenger,23.400,1.9,160.0,100.5,67.6,176.6,2.998,15.8,25.0,2/18/2011,66.113057
V40,Volvo,3.545,NaN,Passenger,24.400,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
S70,Volvo,15.245,NaN,Passenger,27.500,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
V70,Volvo,17.531,NaN,Passenger,28.800,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
C70,Volvo,3.493,NaN,Passenger,45.500,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
S80,Volvo,18.969,NaN,Passenger,36.000,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

In [25]:
df[df["Manufacturer"]=="Toyota"]

,Manufacturer,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
Model,,,,,,,,,,,,,,,
Corolla,Toyota,142.535,10.025,Passenger,13.108,1.8,120.0,97.0,66.7,174.0,2.420,13.2,33.0,4/11/2011,47.968972
Camry,Toyota,247.994,13.245,Passenger,17.518,2.2,133.0,105.2,70.1,188.5,2.998,18.5,27.0,2/10/2011,54.372420
Avalon,Toyota,63.849,18.140,Passenger,25.545,3.0,210.0,107.1,71.7,191.9,3.417,18.5,26.0,8/31/2011,84.911898
Celica,Toyota,33.269,15.445,Passenger,16.875,1.8,140.0,102.4,68.3,170.5,2.425,14.5,31.0,12/29/2012,56.496030
Tacoma,Toyota,84.087,9.575,Car,11.528,2.4,142.0,103.3,66.5,178.7,2.580,15.1,23.0,8/1/2011,55.297117
Sienna,Toyota,65.119,NaN,Car,22.368,3.0,194.0,114.2,73.4,193.5,3.759,20.9,22.0,10/5/2012,78.027219
RAV4,Toyota,25.106,13.325,Car,16.888,2.0,127.0,94.9,66.7,163.8,2.668,15.3,27.0,5/6/2011,51.955109
4Runner,Toyota,68.411,19.425,Car,22.288,2.7,150.0,105.3,66.5,183.3,3.440,18.5,23.0,3/7/2011,62.355577
Land Cruiser,Toyota,9.835,34.080,Car,51.728,4.7,230.0,112.2,76.4,192.5,5.115,25.4,15.0,9/25/2011,102.528984

In [26]:
df[df["Vehicle_type"]=="Passenger"]

,Manufacturer,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
Model,,,,,,,,,,,,,,,
Integra,Acura,16.919,16.360,Passenger,21.500,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
TL,Acura,39.384,19.875,Passenger,28.400,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
CL,Acura,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
RL,Acura,8.588,29.725,Passenger,42.000,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
A4,Audi,20.397,22.255,Passenger,23.990,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
A6,Audi,18.780,23.555,Passenger,33.950,2.8,200.0,108.7,76.1,192.0,3.561,18.5,22.0,8/9/2011,84.565105
A8,Audi,1.380,39.000,Passenger,62.000,4.2,310.0,113.0,74.0,198.2,3.902,23.7,21.0,2/27/2012,134.656858
323i,BMW,19.747,NaN,Passenger,26.990,2.5,170.0,107.3,68.4,176.0,3.179,16.6,26.0,6/28/2011,71.191207
328i,BMW,9.231,28.675,Passenger,33.400,2.8,193.0,107.3,68.5,176.0,3.197,16.6,24.0,1/29/2012,81.877069
528i,BMW,17.527,36.125,Passenger,38.900,2.8,193.0,111.4,70.9,188.0,3.472,18.5,25.0,4/4/2011,83.998724
Century,Buick,91.561,12.475,Passenger,21.975,3.1,175.0,109.0,72.7,194.6,3.368,17.5,25.0,11/2/2011,71.181451
Regal,Buick,39.350,13.740,Passenger,25.300,3.8,240.0,109.0,72.7,196.2,3.543,17.5,23.0,9/3/2011,95.636703
Park Avenue,Buick,27.851,20.190,Passenger,31.965,3.8,205.0,113.8,74.7,206.8,3.778,18.5,24.0,3/23/2012,85.828408
LeSabre,Buick,83.257,13.360,Passenger,27.885,3.8,205.0,112.2,73.5,200.0,3.591,17.5,25.0,7/23/2011,84.254526
DeVille,Cadillac,63.729,22.525,Passenger,39.895,4.6,275.0,115.3,74.5,207.2,3.978,18.5,22.0,2/23/2012,113.854598
Seville,Cadillac,15.943,27.100,Passenger,44.475,4.6,275.0,112.2,75.0,201.0,NaN,18.5,22.0,4/29/2011,115.621358
Eldorado,Cadillac,6.536,25.725,Passenger,39.665,4.6,275.0,108.0,75.5,200.6,3.843,19.0,22.0,11/27/2011,113.765874
Catera,Cadillac,11.185,18.225,Passenger,31.010,3.0,200.0,107.4,70.3,194.8,3.770,18.0,22.0,9/28/2011,83.483094
Cavalier,Chevrolet,145.519,9.250,Passenger,13.260,2.2,115.0,104.1,67.9,180.9,2.676,14.3,27.0,8/17/2011,46.363347
Malibu,Chevrolet,135.126,11.225,Passenger,16.535,3.1,170.0,107.0,69.4,190.4,3.051,15.0,25.0,3/19/2012,67.314462
Lumina,Chevrolet,24.629,10.310,Passenger,18.890,3.1,175.0,107.5,72.5,200.9,3.330,16.6,25.0,5/24/2011,69.991396
Monte Carlo,Chevrolet,42.593,11.525,Passenger,19.390,3.4,180.0,110.5,72.7,197.9,3.340,17.0,27.0,12/22/2011,72.030917
Camaro,Chevrolet,26.402,13.025,Passenger,24.340,3.8,200.0,101.1,74.1,193.2,3.500,16.8,25.0,10/23/2011,81.118543
Corvette,Chevrolet,17.947,36.225,Passenger,45.705,5.7,345.0,104.5,73.6,179.7,3.210,19.1,22.0,5/12/2012,141.141150
Prizm,Chevrolet,32.299,9.125,Passenger,13.960,1.8,120.0,97.1,66.7,174.3,2.398,13.2,33.0,9/11/2011,48.297636
Metro,Chevrolet,21.855,5.160,Passenger,9.235,1.0,55.0,93.1,62.6,149.4,1.895,10.3,45.0,4/13/2012,23.276272
Impala,Chevrolet,107.995,NaN,Passenger,18.890,3.4,180.0,110.5,73.0,200.0,3.389,17.0,27.0,6/18/2011,71.838039
Sebring Coupe,Chrysler,7.854,12.360,Passenger,19.840,2.5,163.0,103.7,69.7,190.9,2.967,15.9,24.0,1/16/2012,65.957184
Sebring Conv.,Chrysler,32.775,14.180,Passenger,24.495,2.5,168.0,106.0,69.2,193.0,3.332,16.0,24.0,11/17/2011,69.521355
Concorde,Chrysler,31.148,13.725,Passenger,22.245,2.7,200.0,113.0,74.4,209.1,3.452,17.0,26.0,6/6/2012,80.023782
Cirrus,Chrysler,32.306,12.640,Passenger,16.480,2.0,132.0,108.0,71.0,186.0,2.911,16.0,27.0,10/6/2011,53.566200
LHS,Chrysler,13.462,17.325,Passenger,28.340,3.5,253.0,113.0,74.4,207.7,3.564,17.0,23.0,5/8/2012,101.329281
300M,Chrysler,30.696,NaN,Passenger,29.185,3.5,253.0,113.0,74.4,197.8,3.567,17.0,23.0,2/10/2012,101.655244
Neon,Dodge,76.034,7.750,Passenger,12.640,2.0,132.0,105.0,74.4,174.4,2.567,12.5,29.0,12/12/2011,52.084899
Avenger,Dodge,4.734,12.545,Passenger,19.045,2.5,163.0,103.7,69.1,190.2,2.879,15.9,24.0,7/1/2012,65.650508
Stratus,Dodge,71.186,10.185,Passenger,20.230,2.5,168.0,108.0,71.0,186.0,3.058,16.0,24.0,10/31/2011,67.876108
Intrepid,Dodge,88.028,12.275,Passenger,22.505,2.7,202.0,113.0,74.7,203.7,3.489,17.0,NaN,6/2/2012,80.831470
Viper,Dodge,0.916,58.470,Passenger,69.725,8.0,450.0,96.2,75.7,176.7,3.375,19.0,16.0,8/7/2011,188.144323
Escort,Ford,70.227,7.425,Passenger,12.070,2.0,110.0,98.4,67.0,174.7,2.468,12.7,30.0,3/31/2012,44.083709
Mustang,Ford,113.369,12.760,Passenger,21.560,3.8,190.0,101.3,73.1,183.2,3.203,15.7,24.0,1/31/2012,76.509185
Contour,Ford,35.068,8.835,Passenger,17.035,2.5,170.0,106.5,69.1,184.6,2.769,15.0,25.0,8/20/2012,67.351011
Taurus,Ford,245.815,10.055,Passenger,17.885,3.0,155.0,108.5,73.0,197.6,3.368,16.0,24.0,12/20/2011,62.503740
Focus,Ford,175.670,NaN,Passenger,12.315,2.0,107.0,103.0,66.9,174.8,2.564,13.2,30.0,7/22/2012,43.117132
Crown Victoria,Ford,63.403,14.210,Passenger,22.195,4.6,200.0,114.7,78.2,212.0,3.908,19.0,21.0,9/26/2011,80.499537
Civic,Honda,199.685,9.850,Passenger,12.885,1.6,106.0,103.2,67.1,175.1,2.339,11.9,32.0,10/21/2011,42.879097
Accord,Honda,230.902,13.210,Passenger,15.350,2.3,135.0,106.9,70.3,188.8,2.932,17.1,27.0,5/20/2012,54.269548
Accent,Hyundai,41.184,5.860,Passenger,9.699,1.5,92.0,96.1,65.7,166.7,2.240,11.9,31.0,9/10/2012,36.672284
Elantra,Hyundai,66.692,7.825,Passenger,11.799,2.0,140.0,100.4,66.9,174.0,2.626,14.5,27.0,11/15/2011,54.590045
Sonata,Hyundai,29.450,8.910,Passenger,14.999,2.4,148.0,106.3,71.6,185.4,3.072,17.2,25.0,6/14/2012,58.758249
I30,Infiniti,23.713,19.690,Passenger,29.465,3.0,227.0,108.3,70.2,193.7,3.342,18.5,25.0,4/15/2012,92.436889
S-Type,Jaguar,15.467,NaN,Passenger,42.800,3.0,240.0,114.5,71.6,191.3,3.650,18.4,21.0,11/3/2012,102.178985
ES300,Lexus,24.072,26.975,Passenger,31.505,3.0,210.0,105.1,70.5,190.2,3.373,18.5,23.0,7/9/2012,87.211001
GS300,Lexus,12.698,32.075,Passenger,37.805,3.0,225.0,110.2,70.9,189.2,3.638,19.8,23.0,5/10/2012,94.946698
GS400,Lexus,3.334,NaN,Passenger,46.305,4.0,300.0,110.2,70.9,189.2,3.693,19.8,21.0,11/28/2012,125.013357
LS400,Lexus,6.375,40.375,Passenger,54.005,4.0,290.0,112.2,72.0,196.7,3.890,22.5,22.0,3/29/2012,124.446716
Continental,Lincoln,13.798,20.525,Passenger,39.080,4.6,275.0,109.0,73.6,208.5,3.868,20.0,22.0,8/3/2012,113.540207
Town car,Lincoln,48.911,21.725,Passenger,43.330,4.6,215.0,117.7,78.2,215.3,4.121,19.0,21.0,6/4/2012,93.957917
Mirage,Mitsubishi,26.232,8.325,Passenger,13.987,1.8,113.0,98.4,66.5,173.6,2.250,13.2,30.0,4/23/2012,45.832181
Eclipse,Mitsubishi,42.541,10.395,Passenger,19.047,2.4,154.0,100.8,68.9,175.4,2.910,15.9,24.0,11/24/2012,62.441962
Galant,Mitsubishi,55.616,10.595,Passenger,17.357,2.4,145.0,103.7,68.5,187.8,2.945,16.3,25.0,1/29/2012,58.606773
Diamante,Mitsubishi,5.711,16.575,Passenger,24.997,3.5,210.0,107.1,70.3,194.1,3.443,19.0,22.0,8/28/2012,84.830779
3000GT,Mitsubishi,0.110,20.940,Passenger,25.450,3.0,161.0,97.2,72.4,180.3,3.131,19.8,21.0,6/29/2012,67.544155
Mystique,Mercury,14.351,8.800,Passenger,16.240,2.0,125.0,106.5,69.1,184.8,2.769,15.0,28.0,12/19/2012,50.997748
Cougar,Mercury,26.529,13.890,Passenger,16.540,2.0,125.0,106.4,69.6,185.0,2.892,16.0,30.0,2/23/2012,51.113474
Sable,Mercury,67.956,11.030,Passenger,19.035,3.0,153.0,108.5,73.0,199.7,3.379,16.0,24.0,9/22/2012,62.239967
Grand Marquis,Mercury,81.174,14.875,Passenger,22.605,4.6,200.0,114.7,78.2,212.0,3.958,19.0,21.0,7/24/2012,80.657696
C-Class,Mercedes-B,18.392,26.050,Passenger,31.750,2.3,185.0,105.9,67.7,177.4,3.250,16.4,26.0,4/24/2011,78.280731
E-Class,Mercedes-B,27.602,41.450,Passenger,49.900,3.2,221.0,111.5,70.8,189.4,3.823,21.1,25.0,7/12/2011,98.249737
S-Class,Mercedes-B,16.774,50.375,Passenger,69.700,4.3,275.0,121.5,73.1,203.1,4.133,23.2,21.0,6/13/2011,125.273876
SL-Class,Mercedes-B,3.311,58.600,Passenger,82.600,5.0,302.0,99.0,71.3,177.1,4.125,21.1,20.0,3/17/2011,139.982294
SLK,Mercedes-B,7.998,NaN,Passenger,38.900,2.3,190.0,94.5,67.5,157.9,3.055,15.9,26.0,1/16/2011,82.807362
SLK230,Mercedes-B,1.526,NaN,Passenger,41.000,2.3,185.0,94.5,67.5,157.3,2.975,14.0,27.0,8/6/2011,81.848969
CLK Coupe,Mercedes-B,11.592,NaN,Passenger,41.600,3.2,215.0,105.9,67.8,180.3,3.213,16.4,26.0,7/8/2011,92.925792
CL500,Mercedes-B,0.954,NaN,Passenger,85.500,5.0,302.0,113.6,73.1,196.6,4.115,23.2,20.0,4/11/2011,141.100985
Sentra,Nissan,42.643,8.450,Passenger,13.499,1.8,126.0,99.8,67.3,177.5,2.593,13.2,30.0,8/31/2011,50.241978
Altima,Nissan,88.094,11.295,Passenger,20.390,2.4,155.0,103.1,69.1,183.5,3.012,15.9,25.0,8/2/2011,63.313728
Maxima,Nissan,79.853,15.125,Passenger,26.249,3.0,222.0,108.3,70.3,190.5,3.294,18.5,25.0,5/6/2011,89.427820
Cutlass,Oldsmobile,1.112,11.240,Passenger,18.145,3.1,150.0,107.0,69.4,192.0,3.102,15.2,25.0,5/31/2011,60.861612
Intrigue,Oldsmobile,38.554,NaN,Passenger,24.150,3.5,215.0,109.0,73.6,195.9,3.455,18.0,NaN,4/1/2011,86.272523
Alero,Oldsmobile,80.255,NaN,Passenger,18.270,2.4,150.0,107.0,70.1,186.7,2.958,15.0,27.0,10/20/2009,60.727447
Aurora,Oldsmobile,14.690,19.890,Passenger,36.229,4.0,250.0,113.8,74.4,205.4,3.967,18.5,22.0,2/18/2011,103.441693
Neon,Plymouth,32.734,7.750,Passenger,12.640,2.0,132.0,105.0,74.4,174.4,2.559,12.5,29.0,4/26/2011,52.084899
Breeze,Plymouth,5.240,9.800,Passenger,16.080,2.0,132.0,108.0,71.0,186.3,2.942,16.0,27.0,11/14/2011,53.411898
Prowler,Plymouth,1.872,NaN,Passenger,43.000,3.5,253.0,113.3,76.3,165.4,2.850,12.0,21.0,6/27/2012,106.984456
Sunfire,Pontiac,51.645,13.790,Passenger,21.610,2.4,150.0,104.1,68.4,181.9,2.906,15.0,27.0,1/25/2012,62.015870
Grand Am,Pontiac,131.097,10.290,Passenger,19.720,3.4,175.0,107.0,70.4,186.3,3.091,15.2,25.0,11/26/2012,70.389737
Firebird,Pontiac,19.911,17.805,Passenger,25.310,3.8,200.0,101.1,74.5,193.4,3.492,16.8,25.0,6/16/2012,81.492726
Grand Prix,Pontiac,92.364,14.010,Passenger,21.665,3.8,195.0,110.5,72.7,196.5,3.396,18.0,25.0,10/15/2012,78.318168
Bonneville,Pontiac,35.945,13.225,Passenger,23.755,3.8,205.0,112.2,72.6,202.5,3.590,17.5,24.0,5/18/2011,82.661356
Boxter,Porsche,8.982,41.250,Passenger,41.430,2.7,217.0,95.2,70.1,171.0,2.778,17.0,22.0,2/19/2012,93.437331
Carrera Coupe,Porsche,1.280,60.625,Passenger,71.020,3.4,300.0,92.6,69.5,174.5,3.032,17.0,21.0,12/21/2012,134.390975
Carrera Cabrio,Porsche,1.866,67.550,Passenger,74.970,3.4,300.0,92.6,69.5,174.5,3.075,17.0,23.0,7/11/2011,135.914710
5-Sep,Saab,9.191,NaN,Passenger,33.120,2.3,170.0,106.4,70.6,189.2,3.280,18.5,23.0,11/9/2012,73.503778
3-Sep,Saab,12.115,NaN,Passenger,26.100,2.0,185.0,102.6,67.4,182.2,2.990,16.9,23.0,6/12/2011,76.023048
SL,Saturn,80.620,9.200,Passenger,10.685,1.9,100.0,102.4,66.4,176.9,2.332,12.1,33.0,8/16/2012,39.986425
SC,Saturn,24.546,10.590,Passenger,12.535,1.9,100.0,102.4,66.4,180.0,2.367,12.1,33.0,3/16/2011,40.700072
SW,Saturn,5.223,10.790,Passenger,14.290,1.9,124.0,102.4,66.4,176.9,2.452,12.1,31.0,1/15/2011,49.865774
LW,Saturn,8.472,NaN,Passenger,18.835,2.2,137.0,106.5,69.0,190.4,3.075,13.1,27.0,8/5/2011,56.295243
LS,Saturn,49.989,NaN,Passenger,15.010,2.2,137.0,106.5,69.0,190.4,2.910,13.1,28.0,12/4/2012,54.819728
Outback,Subaru,47.107,NaN,Passenger,22.695,2.5,165.0,103.5,67.5,185.8,3.415,16.9,25.0,7/7/2011,67.765908
Corolla,Toyota,142.535,10.025,Passenger,13.108,1.8,120.0,97.0,66.7,174.0,2.420,13.2,33.0,4/11/2011,47.968972
Camry,Toyota,247.994,13.245,Passenger,17.518,2.2,133.0,105.2,70.1,188.5,2.998,18.5,27.0,2/10/2011,54.372420
Avalon,Toyota,63.849,18.140,Passenger,25.545,3.0,210.0,107.1,71.7,191.9,3.417,18.5,26.0,8/31/2011,84.911898
Celica,Toyota,33.269,15.445,Passenger,16.875,1.8,140.0,102.4,68.3,170.5,2.425,14.5,31.0,12/29/2012,56.496030
Golf,Volkswagen,9.761,11.425,Passenger,14.900,2.0,115.0,98.9,68.3,163.3,2.767,14.5,26.0,1/24/2011,46.943877
Jetta,Volkswagen,83.721,13.240,Passenger,16.700,2.0,115.0,98.9,68.3,172.3,2.853,14.5,26.0,8/27/2011,47.638237
Passat,Volkswagen,51.102,16.725,Passenger,21.200,1.8,150.0,106.4,68.5,184.1,3.043,16.4,27.0,10/30/2012,61.701381
Cabrio,Volkswagen,9.569,16.575,Passenger,19.990,2.0,115.0,97.4,66.7,160.4,3.079,13.7,26.0,5/31/2011,48.907372
GTI,Volkswagen,5.596,13.760,Passenger,17.500,2.0,115.0,98.9,68.3,163.3,2.762,14.6,26.0,4/1/2011,47.946841
Beetle,Volkswagen,49.463,NaN,Passenger,15.900,2.0,115.0,98.9,67.9,161.1,2.769,14.5,26.0,10/20/2011,47.329632
S40,Volvo,16.957,NaN,Passenger,23.400,1.9,160.0,100.5,67.6,176.6,2.998,15.8,25.0,2/18/2011,66.113057
V40,Volvo,3.545,NaN,Passenger,24.400,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
S70,Volvo,15.245,NaN,Passenger,27.500,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
V70,Volvo,17.531,NaN,Passenger,28.800,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
C70,Volvo,3.493,NaN,Passenger,45.500,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
S80,Volvo,18.969,NaN,Passenger,36.000,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

In [27]:
df[(df["Manufacturer"]=="Toyota") & (df["Vehicle_type"]=="Passenger")]

,Manufacturer,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
Model,,,,,,,,,,,,,,,
Corolla,Toyota,142.535,10.025,Passenger,13.108,1.8,120.0,97.0,66.7,174.0,2.420,13.2,33.0,4/11/2011,47.968972
Camry,Toyota,247.994,13.245,Passenger,17.518,2.2,133.0,105.2,70.1,188.5,2.998,18.5,27.0,2/10/2011,54.372420
Avalon,Toyota,63.849,18.140,Passenger,25.545,3.0,210.0,107.1,71.7,191.9,3.417,18.5,26.0,8/31/2011,84.911898
Celica,Toyota,33.269,15.445,Passenger,16.875,1.8,140.0,102.4,68.3,170.5,2.425,14.5,31.0,12/29/2012,56.496030

In [28]:
df[(df["Manufacturer"]=="Toyota") | (df["Vehicle_type"]=="Passenger")]

,Manufacturer,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
Model,,,,,,,,,,,,,,,
Integra,Acura,16.919,16.360,Passenger,21.500,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
TL,Acura,39.384,19.875,Passenger,28.400,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
CL,Acura,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
RL,Acura,8.588,29.725,Passenger,42.000,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
A4,Audi,20.397,22.255,Passenger,23.990,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
A6,Audi,18.780,23.555,Passenger,33.950,2.8,200.0,108.7,76.1,192.0,3.561,18.5,22.0,8/9/2011,84.565105
A8,Audi,1.380,39.000,Passenger,62.000,4.2,310.0,113.0,74.0,198.2,3.902,23.7,21.0,2/27/2012,134.656858
323i,BMW,19.747,NaN,Passenger,26.990,2.5,170.0,107.3,68.4,176.0,3.179,16.6,26.0,6/28/2011,71.191207
328i,BMW,9.231,28.675,Passenger,33.400,2.8,193.0,107.3,68.5,176.0,3.197,16.6,24.0,1/29/2012,81.877069
528i,BMW,17.527,36.125,Passenger,38.900,2.8,193.0,111.4,70.9,188.0,3.472,18.5,25.0,4/4/2011,83.998724
Century,Buick,91.561,12.475,Passenger,21.975,3.1,175.0,109.0,72.7,194.6,3.368,17.5,25.0,11/2/2011,71.181451
Regal,Buick,39.350,13.740,Passenger,25.300,3.8,240.0,109.0,72.7,196.2,3.543,17.5,23.0,9/3/2011,95.636703
Park Avenue,Buick,27.851,20.190,Passenger,31.965,3.8,205.0,113.8,74.7,206.8,3.778,18.5,24.0,3/23/2012,85.828408
LeSabre,Buick,83.257,13.360,Passenger,27.885,3.8,205.0,112.2,73.5,200.0,3.591,17.5,25.0,7/23/2011,84.254526
DeVille,Cadillac,63.729,22.525,Passenger,39.895,4.6,275.0,115.3,74.5,207.2,3.978,18.5,22.0,2/23/2012,113.854598
Seville,Cadillac,15.943,27.100,Passenger,44.475,4.6,275.0,112.2,75.0,201.0,NaN,18.5,22.0,4/29/2011,115.621358
Eldorado,Cadillac,6.536,25.725,Passenger,39.665,4.6,275.0,108.0,75.5,200.6,3.843,19.0,22.0,11/27/2011,113.765874
Catera,Cadillac,11.185,18.225,Passenger,31.010,3.0,200.0,107.4,70.3,194.8,3.770,18.0,22.0,9/28/2011,83.483094
Cavalier,Chevrolet,145.519,9.250,Passenger,13.260,2.2,115.0,104.1,67.9,180.9,2.676,14.3,27.0,8/17/2011,46.363347
Malibu,Chevrolet,135.126,11.225,Passenger,16.535,3.1,170.0,107.0,69.4,190.4,3.051,15.0,25.0,3/19/2012,67.314462
Lumina,Chevrolet,24.629,10.310,Passenger,18.890,3.1,175.0,107.5,72.5,200.9,3.330,16.6,25.0,5/24/2011,69.991396
Monte Carlo,Chevrolet,42.593,11.525,Passenger,19.390,3.4,180.0,110.5,72.7,197.9,3.340,17.0,27.0,12/22/2011,72.030917
Camaro,Chevrolet,26.402,13.025,Passenger,24.340,3.8,200.0,101.1,74.1,193.2,3.500,16.8,25.0,10/23/2011,81.118543
Corvette,Chevrolet,17.947,36.225,Passenger,45.705,5.7,345.0,104.5,73.6,179.7,3.210,19.1,22.0,5/12/2012,141.141150
Prizm,Chevrolet,32.299,9.125,Passenger,13.960,1.8,120.0,97.1,66.7,174.3,2.398,13.2,33.0,9/11/2011,48.297636
Metro,Chevrolet,21.855,5.160,Passenger,9.235,1.0,55.0,93.1,62.6,149.4,1.895,10.3,45.0,4/13/2012,23.276272
Impala,Chevrolet,107.995,NaN,Passenger,18.890,3.4,180.0,110.5,73.0,200.0,3.389,17.0,27.0,6/18/2011,71.838039
Sebring Coupe,Chrysler,7.854,12.360,Passenger,19.840,2.5,163.0,103.7,69.7,190.9,2.967,15.9,24.0,1/16/2012,65.957184
Sebring Conv.,Chrysler,32.775,14.180,Passenger,24.495,2.5,168.0,106.0,69.2,193.0,3.332,16.0,24.0,11/17/2011,69.521355
Concorde,Chrysler,31.148,13.725,Passenger,22.245,2.7,200.0,113.0,74.4,209.1,3.452,17.0,26.0,6/6/2012,80.023782
Cirrus,Chrysler,32.306,12.640,Passenger,16.480,2.0,132.0,108.0,71.0,186.0,2.911,16.0,27.0,10/6/2011,53.566200
LHS,Chrysler,13.462,17.325,Passenger,28.340,3.5,253.0,113.0,74.4,207.7,3.564,17.0,23.0,5/8/2012,101.329281
300M,Chrysler,30.696,NaN,Passenger,29.185,3.5,253.0,113.0,74.4,197.8,3.567,17.0,23.0,2/10/2012,101.655244
Neon,Dodge,76.034,7.750,Passenger,12.640,2.0,132.0,105.0,74.4,174.4,2.567,12.5,29.0,12/12/2011,52.084899
Avenger,Dodge,4.734,12.545,Passenger,19.045,2.5,163.0,103.7,69.1,190.2,2.879,15.9,24.0,7/1/2012,65.650508
Stratus,Dodge,71.186,10.185,Passenger,20.230,2.5,168.0,108.0,71.0,186.0,3.058,16.0,24.0,10/31/2011,67.876108
Intrepid,Dodge,88.028,12.275,Passenger,22.505,2.7,202.0,113.0,74.7,203.7,3.489,17.0,NaN,6/2/2012,80.831470
Viper,Dodge,0.916,58.470,Passenger,69.725,8.0,450.0,96.2,75.7,176.7,3.375,19.0,16.0,8/7/2011,188.144323
Escort,Ford,70.227,7.425,Passenger,12.070,2.0,110.0,98.4,67.0,174.7,2.468,12.7,30.0,3/31/2012,44.083709
Mustang,Ford,113.369,12.760,Passenger,21.560,3.8,190.0,101.3,73.1,183.2,3.203,15.7,24.0,1/31/2012,76.509185
Contour,Ford,35.068,8.835,Passenger,17.035,2.5,170.0,106.5,69.1,184.6,2.769,15.0,25.0,8/20/2012,67.351011
Taurus,Ford,245.815,10.055,Passenger,17.885,3.0,155.0,108.5,73.0,197.6,3.368,16.0,24.0,12/20/2011,62.503740
Focus,Ford,175.670,NaN,Passenger,12.315,2.0,107.0,103.0,66.9,174.8,2.564,13.2,30.0,7/22/2012,43.117132
Crown Victoria,Ford,63.403,14.210,Passenger,22.195,4.6,200.0,114.7,78.2,212.0,3.908,19.0,21.0,9/26/2011,80.499537
Civic,Honda,199.685,9.850,Passenger,12.885,1.6,106.0,103.2,67.1,175.1,2.339,11.9,32.0,10/21/2011,42.879097
Accord,Honda,230.902,13.210,Passenger,15.350,2.3,135.0,106.9,70.3,188.8,2.932,17.1,27.0,5/20/2012,54.269548
Accent,Hyundai,41.184,5.860,Passenger,9.699,1.5,92.0,96.1,65.7,166.7,2.240,11.9,31.0,9/10/2012,36.672284
Elantra,Hyundai,66.692,7.825,Passenger,11.799,2.0,140.0,100.4,66.9,174.0,2.626,14.5,27.0,11/15/2011,54.590045
Sonata,Hyundai,29.450,8.910,Passenger,14.999,2.4,148.0,106.3,71.6,185.4,3.072,17.2,25.0,6/14/2012,58.758249
I30,Infiniti,23.713,19.690,Passenger,29.465,3.0,227.0,108.3,70.2,193.7,3.342,18.5,25.0,4/15/2012,92.436889
S-Type,Jaguar,15.467,NaN,Passenger,42.800,3.0,240.0,114.5,71.6,191.3,3.650,18.4,21.0,11/3/2012,102.178985
ES300,Lexus,24.072,26.975,Passenger,31.505,3.0,210.0,105.1,70.5,190.2,3.373,18.5,23.0,7/9/2012,87.211001
GS300,Lexus,12.698,32.075,Passenger,37.805,3.0,225.0,110.2,70.9,189.2,3.638,19.8,23.0,5/10/2012,94.946698
GS400,Lexus,3.334,NaN,Passenger,46.305,4.0,300.0,110.2,70.9,189.2,3.693,19.8,21.0,11/28/2012,125.013357
LS400,Lexus,6.375,40.375,Passenger,54.005,4.0,290.0,112.2,72.0,196.7,3.890,22.5,22.0,3/29/2012,124.446716
Continental,Lincoln,13.798,20.525,Passenger,39.080,4.6,275.0,109.0,73.6,208.5,3.868,20.0,22.0,8/3/2012,113.540207
Town car,Lincoln,48.911,21.725,Passenger,43.330,4.6,215.0,117.7,78.2,215.3,4.121,19.0,21.0,6/4/2012,93.957917
Mirage,Mitsubishi,26.232,8.325,Passenger,13.987,1.8,113.0,98.4,66.5,173.6,2.250,13.2,30.0,4/23/2012,45.832181
Eclipse,Mitsubishi,42.541,10.395,Passenger,19.047,2.4,154.0,100.8,68.9,175.4,2.910,15.9,24.0,11/24/2012,62.441962
Galant,Mitsubishi,55.616,10.595,Passenger,17.357,2.4,145.0,103.7,68.5,187.8,2.945,16.3,25.0,1/29/2012,58.606773
Diamante,Mitsubishi,5.711,16.575,Passenger,24.997,3.5,210.0,107.1,70.3,194.1,3.443,19.0,22.0,8/28/2012,84.830779
3000GT,Mitsubishi,0.110,20.940,Passenger,25.450,3.0,161.0,97.2,72.4,180.3,3.131,19.8,21.0,6/29/2012,67.544155
Mystique,Mercury,14.351,8.800,Passenger,16.240,2.0,125.0,106.5,69.1,184.8,2.769,15.0,28.0,12/19/2012,50.997748
Cougar,Mercury,26.529,13.890,Passenger,16.540,2.0,125.0,106.4,69.6,185.0,2.892,16.0,30.0,2/23/2012,51.113474
Sable,Mercury,67.956,11.030,Passenger,19.035,3.0,153.0,108.5,73.0,199.7,3.379,16.0,24.0,9/22/2012,62.239967
Grand Marquis,Mercury,81.174,14.875,Passenger,22.605,4.6,200.0,114.7,78.2,212.0,3.958,19.0,21.0,7/24/2012,80.657696
C-Class,Mercedes-B,18.392,26.050,Passenger,31.750,2.3,185.0,105.9,67.7,177.4,3.250,16.4,26.0,4/24/2011,78.280731
E-Class,Mercedes-B,27.602,41.450,Passenger,49.900,3.2,221.0,111.5,70.8,189.4,3.823,21.1,25.0,7/12/2011,98.249737
S-Class,Mercedes-B,16.774,50.375,Passenger,69.700,4.3,275.0,121.5,73.1,203.1,4.133,23.2,21.0,6/13/2011,125.273876
SL-Class,Mercedes-B,3.311,58.600,Passenger,82.600,5.0,302.0,99.0,71.3,177.1,4.125,21.1,20.0,3/17/2011,139.982294
SLK,Mercedes-B,7.998,NaN,Passenger,38.900,2.3,190.0,94.5,67.5,157.9,3.055,15.9,26.0,1/16/2011,82.807362
SLK230,Mercedes-B,1.526,NaN,Passenger,41.000,2.3,185.0,94.5,67.5,157.3,2.975,14.0,27.0,8/6/2011,81.848969
CLK Coupe,Mercedes-B,11.592,NaN,Passenger,41.600,3.2,215.0,105.9,67.8,180.3,3.213,16.4,26.0,7/8/2011,92.925792
CL500,Mercedes-B,0.954,NaN,Passenger,85.500,5.0,302.0,113.6,73.1,196.6,4.115,23.2,20.0,4/11/2011,141.100985
Sentra,Nissan,42.643,8.450,Passenger,13.499,1.8,126.0,99.8,67.3,177.5,2.593,13.2,30.0,8/31/2011,50.241978
Altima,Nissan,88.094,11.295,Passenger,20.390,2.4,155.0,103.1,69.1,183.5,3.012,15.9,25.0,8/2/2011,63.313728
Maxima,Nissan,79.853,15.125,Passenger,26.249,3.0,222.0,108.3,70.3,190.5,3.294,18.5,25.0,5/6/2011,89.427820
Cutlass,Oldsmobile,1.112,11.240,Passenger,18.145,3.1,150.0,107.0,69.4,192.0,3.102,15.2,25.0,5/31/2011,60.861612
Intrigue,Oldsmobile,38.554,NaN,Passenger,24.150,3.5,215.0,109.0,73.6,195.9,3.455,18.0,NaN,4/1/2011,86.272523
Alero,Oldsmobile,80.255,NaN,Passenger,18.270,2.4,150.0,107.0,70.1,186.7,2.958,15.0,27.0,10/20/2009,60.727447
Aurora,Oldsmobile,14.690,19.890,Passenger,36.229,4.0,250.0,113.8,74.4,205.4,3.967,18.5,22.0,2/18/2011,103.441693
Neon,Plymouth,32.734,7.750,Passenger,12.640,2.0,132.0,105.0,74.4,174.4,2.559,12.5,29.0,4/26/2011,52.084899
Breeze,Plymouth,5.240,9.800,Passenger,16.080,2.0,132.0,108.0,71.0,186.3,2.942,16.0,27.0,11/14/2011,53.411898
Prowler,Plymouth,1.872,NaN,Passenger,43.000,3.5,253.0,113.3,76.3,165.4,2.850,12.0,21.0,6/27/2012,106.984456
Sunfire,Pontiac,51.645,13.790,Passenger,21.610,2.4,150.0,104.1,68.4,181.9,2.906,15.0,27.0,1/25/2012,62.015870
Grand Am,Pontiac,131.097,10.290,Passenger,19.720,3.4,175.0,107.0,70.4,186.3,3.091,15.2,25.0,11/26/2012,70.389737
Firebird,Pontiac,19.911,17.805,Passenger,25.310,3.8,200.0,101.1,74.5,193.4,3.492,16.8,25.0,6/16/2012,81.492726
Grand Prix,Pontiac,92.364,14.010,Passenger,21.665,3.8,195.0,110.5,72.7,196.5,3.396,18.0,25.0,10/15/2012,78.318168
Bonneville,Pontiac,35.945,13.225,Passenger,23.755,3.8,205.0,112.2,72.6,202.5,3.590,17.5,24.0,5/18/2011,82.661356
Boxter,Porsche,8.982,41.250,Passenger,41.430,2.7,217.0,95.2,70.1,171.0,2.778,17.0,22.0,2/19/2012,93.437331
Carrera Coupe,Porsche,1.280,60.625,Passenger,71.020,3.4,300.0,92.6,69.5,174.5,3.032,17.0,21.0,12/21/2012,134.390975
Carrera Cabrio,Porsche,1.866,67.550,Passenger,74.970,3.4,300.0,92.6,69.5,174.5,3.075,17.0,23.0,7/11/2011,135.914710
5-Sep,Saab,9.191,NaN,Passenger,33.120,2.3,170.0,106.4,70.6,189.2,3.280,18.5,23.0,11/9/2012,73.503778
3-Sep,Saab,12.115,NaN,Passenger,26.100,2.0,185.0,102.6,67.4,182.2,2.990,16.9,23.0,6/12/2011,76.023048
SL,Saturn,80.620,9.200,Passenger,10.685,1.9,100.0,102.4,66.4,176.9,2.332,12.1,33.0,8/16/2012,39.986425
SC,Saturn,24.546,10.590,Passenger,12.535,1.9,100.0,102.4,66.4,180.0,2.367,12.1,33.0,3/16/2011,40.700072
SW,Saturn,5.223,10.790,Passenger,14.290,1.9,124.0,102.4,66.4,176.9,2.452,12.1,31.0,1/15/2011,49.865774
LW,Saturn,8.472,NaN,Passenger,18.835,2.2,137.0,106.5,69.0,190.4,3.075,13.1,27.0,8/5/2011,56.295243
LS,Saturn,49.989,NaN,Passenger,15.010,2.2,137.0,106.5,69.0,190.4,2.910,13.1,28.0,12/4/2012,54.819728
Outback,Subaru,47.107,NaN,Passenger,22.695,2.5,165.0,103.5,67.5,185.8,3.415,16.9,25.0,7/7/2011,67.765908
Corolla,Toyota,142.535,10.025,Passenger,13.108,1.8,120.0,97.0,66.7,174.0,2.420,13.2,33.0,4/11/2011,47.968972
Camry,Toyota,247.994,13.245,Passenger,17.518,2.2,133.0,105.2,70.1,188.5,2.998,18.5,27.0,2/10/2011,54.372420
Avalon,Toyota,63.849,18.140,Passenger,25.545,3.0,210.0,107.1,71.7,191.9,3.417,18.5,26.0,8/31/2011,84.911898
Celica,Toyota,33.269,15.445,Passenger,16.875,1.8,140.0,102.4,68.3,170.5,2.425,14.5,31.0,12/29/2012,56.496030
Tacoma,Toyota,84.087,9.575,Car,11.528,2.4,142.0,103.3,66.5,178.7,2.580,15.1,23.0,8/1/2011,55.297117
Sienna,Toyota,65.119,NaN,Car,22.368,3.0,194.0,114.2,73.4,193.5,3.759,20.9,22.0,10/5/2012,78.027219
RAV4,Toyota,25.106,13.325,Car,16.888,2.0,127.0,94.9,66.7,163.8,2.668,15.3,27.0,5/6/2011,51.955109
4Runner,Toyota,68.411,19.425,Car,22.288,2.7,150.0,105.3,66.5,183.3,3.440,18.5,23.0,3/7/2011,62.355577
Land Cruiser,Toyota,9.835,34.080,Car,51.728,4.7,230.0,112.2,76.4,192.5,5.115,25.4,15.0,9/25/2011,102.528984
Golf,Volkswagen,9.761,11.425,Passenger,14.900,2.0,115.0,98.9,68.3,163.3,2.767,14.5,26.0,1/24/2011,46.943877
Jetta,Volkswagen,83.721,13.240,Passenger,16.700,2.0,115.0,98.9,68.3,172.3,2.853,14.5,26.0,8/27/2011,47.638237
Passat,Volkswagen,51.102,16.725,Passenger,21.200,1.8,150.0,106.4,68.5,184.1,3.043,16.4,27.0,10/30/2012,61.701381
Cabrio,Volkswagen,9.569,16.575,Passenger,19.990,2.0,115.0,97.4,66.7,160.4,3.079,13.7,26.0,5/31/2011,48.907372
GTI,Volkswagen,5.596,13.760,Passenger,17.500,2.0,115.0,98.9,68.3,163.3,2.762,14.6,26.0,4/1/2011,47.946841
Beetle,Volkswagen,49.463,NaN,Passenger,15.900,2.0,115.0,98.9,67.9,161.1,2.769,14.5,26.0,10/20/2011,47.329632
S40,Volvo,16.957,NaN,Passenger,23.400,1.9,160.0,100.5,67.6,176.6,2.998,15.8,25.0,2/18/2011,66.113057
V40,Volvo,3.545,NaN,Passenger,24.400,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
S70,Volvo,15.245,NaN,Passenger,27.500,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
V70,Volvo,17.531,NaN,Passenger,28.800,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
C70,Volvo,3.493,NaN,Passenger,45.500,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
S80,Volvo,18.969,NaN,Passenger,36.000,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

In [29]:
df[df["Horsepower"]>=200]

,Manufacturer,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
Model,,,,,,,,,,,,,,,
TL,Acura,39.384,19.875,Passenger,28.400,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
CL,Acura,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
RL,Acura,8.588,29.725,Passenger,42.000,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
A6,Audi,18.780,23.555,Passenger,33.950,2.8,200.0,108.7,76.1,192.0,3.561,18.5,22.0,8/9/2011,84.565105
A8,Audi,1.380,39.000,Passenger,62.000,4.2,310.0,113.0,74.0,198.2,3.902,23.7,21.0,2/27/2012,134.656858
Regal,Buick,39.350,13.740,Passenger,25.300,3.8,240.0,109.0,72.7,196.2,3.543,17.5,23.0,9/3/2011,95.636703
Park Avenue,Buick,27.851,20.190,Passenger,31.965,3.8,205.0,113.8,74.7,206.8,3.778,18.5,24.0,3/23/2012,85.828408
LeSabre,Buick,83.257,13.360,Passenger,27.885,3.8,205.0,112.2,73.5,200.0,3.591,17.5,25.0,7/23/2011,84.254526
DeVille,Cadillac,63.729,22.525,Passenger,39.895,4.6,275.0,115.3,74.5,207.2,3.978,18.5,22.0,2/23/2012,113.854598
Seville,Cadillac,15.943,27.100,Passenger,44.475,4.6,275.0,112.2,75.0,201.0,NaN,18.5,22.0,4/29/2011,115.621358
Eldorado,Cadillac,6.536,25.725,Passenger,39.665,4.6,275.0,108.0,75.5,200.6,3.843,19.0,22.0,11/27/2011,113.765874
Catera,Cadillac,11.185,18.225,Passenger,31.010,3.0,200.0,107.4,70.3,194.8,3.770,18.0,22.0,9/28/2011,83.483094
Escalade,Cadillac,14.785,NaN,Car,46.225,5.7,255.0,117.5,77.0,201.2,5.572,30.0,15.0,4/17/2012,109.509117
Camaro,Chevrolet,26.402,13.025,Passenger,24.340,3.8,200.0,101.1,74.1,193.2,3.500,16.8,25.0,10/23/2011,81.118543
Corvette,Chevrolet,17.947,36.225,Passenger,45.705,5.7,345.0,104.5,73.6,179.7,3.210,19.1,22.0,5/12/2012,141.141150
Concorde,Chrysler,31.148,13.725,Passenger,22.245,2.7,200.0,113.0,74.4,209.1,3.452,17.0,26.0,6/6/2012,80.023782
LHS,Chrysler,13.462,17.325,Passenger,28.340,3.5,253.0,113.0,74.4,207.7,3.564,17.0,23.0,5/8/2012,101.329281
300M,Chrysler,30.696,NaN,Passenger,29.185,3.5,253.0,113.0,74.4,197.8,3.567,17.0,23.0,2/10/2012,101.655244
Intrepid,Dodge,88.028,12.275,Passenger,22.505,2.7,202.0,113.0,74.7,203.7,3.489,17.0,NaN,6/2/2012,80.831470
Viper,Dodge,0.916,58.470,Passenger,69.725,8.0,450.0,96.2,75.7,176.7,3.375,19.0,16.0,8/7/2011,188.144323
Ram Pickup,Dodge,227.061,15.060,Car,19.460,5.2,230.0,138.7,79.3,224.2,4.470,26.0,17.0,3/6/2012,90.211700
Durango,Dodge,101.323,NaN,Car,26.310,5.2,230.0,115.7,71.7,193.5,4.394,25.0,17.0,6/27/2012,92.854125
Crown Victoria,Ford,63.403,14.210,Passenger,22.195,4.6,200.0,114.7,78.2,212.0,3.908,19.0,21.0,9/26/2011,80.499537
Explorer,Ford,276.747,16.640,Car,31.930,4.0,210.0,111.6,70.2,190.7,3.876,21.0,19.0,4/25/2012,87.635496
Expedition,Ford,125.338,23.575,Car,36.135,4.6,240.0,119.0,78.7,204.6,4.808,26.0,16.0,9/14/2012,100.024802
F-Series,Ford,540.561,15.075,Car,26.935,4.6,220.0,138.5,79.1,224.5,4.241,25.1,18.0,8/16/2012,89.401935
Passport,Honda,12.855,17.525,Car,26.600,3.2,205.0,106.4,70.4,178.2,3.857,21.1,19.0,10/9/2012,83.602501
Odyssey,Honda,76.029,19.490,Car,26.000,3.5,210.0,118.1,75.6,201.2,4.288,20.0,23.0,2/8/2012,85.217691
I30,Infiniti,23.713,19.690,Passenger,29.465,3.0,227.0,108.3,70.2,193.7,3.342,18.5,25.0,4/15/2012,92.436889
S-Type,Jaguar,15.467,NaN,Passenger,42.800,3.0,240.0,114.5,71.6,191.3,3.650,18.4,21.0,11/3/2012,102.178985
ES300,Lexus,24.072,26.975,Passenger,31.505,3.0,210.0,105.1,70.5,190.2,3.373,18.5,23.0,7/9/2012,87.211001
GS300,Lexus,12.698,32.075,Passenger,37.805,3.0,225.0,110.2,70.9,189.2,3.638,19.8,23.0,5/10/2012,94.946698
GS400,Lexus,3.334,NaN,Passenger,46.305,4.0,300.0,110.2,70.9,189.2,3.693,19.8,21.0,11/28/2012,125.013357
LS400,Lexus,6.375,40.375,Passenger,54.005,4.0,290.0,112.2,72.0,196.7,3.890,22.5,22.0,3/29/2012,124.446716
LX470,Lexus,9.126,NaN,Car,60.105,4.7,230.0,112.2,76.4,192.5,5.401,25.4,15.0,10/30/2012,105.760458
RX300,Lexus,51.238,NaN,Car,34.605,3.0,220.0,103.0,71.5,180.1,3.900,17.2,21.0,1/4/2012,91.943802
Continental,Lincoln,13.798,20.525,Passenger,39.080,4.6,275.0,109.0,73.6,208.5,3.868,20.0,22.0,8/3/2012,113.540207
Town car,Lincoln,48.911,21.725,Passenger,43.330,4.6,215.0,117.7,78.2,215.3,4.121,19.0,21.0,6/4/2012,93.957917
Navigator,Lincoln,22.925,NaN,Car,42.660,5.4,300.0,119.0,79.9,204.8,5.393,30.0,15.0,12/23/2012,123.972047
Diamante,Mitsubishi,5.711,16.575,Passenger,24.997,3.5,210.0,107.1,70.3,194.1,3.443,19.0,22.0,8/28/2012,84.830779
Montero,Mitsubishi,11.337,19.125,Car,31.807,3.5,200.0,107.3,69.9,186.6,4.520,24.3,18.0,1/17/2012,83.920815
Grand Marquis,Mercury,81.174,14.875,Passenger,22.605,4.6,200.0,114.7,78.2,212.0,3.958,19.0,21.0,7/24/2012,80.657696
Mountaineer,Mercury,27.609,20.430,Car,27.560,4.0,210.0,111.6,70.2,190.1,3.876,21.0,18.0,2/13/2008,85.949744
E-Class,Mercedes-B,27.602,41.450,Passenger,49.900,3.2,221.0,111.5,70.8,189.4,3.823,21.1,25.0,7/12/2011,98.249737
S-Class,Mercedes-B,16.774,50.375,Passenger,69.700,4.3,275.0,121.5,73.1,203.1,4.133,23.2,21.0,6/13/2011,125.273876
SL-Class,Mercedes-B,3.311,58.600,Passenger,82.600,5.0,302.0,99.0,71.3,177.1,4.125,21.1,20.0,3/17/2011,139.982294
CLK Coupe,Mercedes-B,11.592,NaN,Passenger,41.600,3.2,215.0,105.9,67.8,180.3,3.213,16.4,26.0,7/8/2011,92.925792
CL500,Mercedes-B,0.954,NaN,Passenger,85.500,5.0,302.0,113.6,73.1,196.6,4.115,23.2,20.0,4/11/2011,141.100985
M-Class,Mercedes-B,28.976,NaN,Car,35.300,3.2,215.0,111.0,72.2,180.6,4.387,19.0,20.0,2/10/2011,90.495532
Maxima,Nissan,79.853,15.125,Passenger,26.249,3.0,222.0,108.3,70.3,190.5,3.294,18.5,25.0,5/6/2011,89.427820
Intrigue,Oldsmobile,38.554,NaN,Passenger,24.150,3.5,215.0,109.0,73.6,195.9,3.455,18.0,NaN,4/1/2011,86.272523
Aurora,Oldsmobile,14.690,19.890,Passenger,36.229,4.0,250.0,113.8,74.4,205.4,3.967,18.5,22.0,2/18/2011,103.441693
Prowler,Plymouth,1.872,NaN,Passenger,43.000,3.5,253.0,113.3,76.3,165.4,2.850,12.0,21.0,6/27/2012,106.984456
Firebird,Pontiac,19.911,17.805,Passenger,25.310,3.8,200.0,101.1,74.5,193.4,3.492,16.8,25.0,6/16/2012,81.492726
Bonneville,Pontiac,35.945,13.225,Passenger,23.755,3.8,205.0,112.2,72.6,202.5,3.590,17.5,24.0,5/18/2011,82.661356
Boxter,Porsche,8.982,41.250,Passenger,41.430,2.7,217.0,95.2,70.1,171.0,2.778,17.0,22.0,2/19/2012,93.437331
Carrera Coupe,Porsche,1.280,60.625,Passenger,71.020,3.4,300.0,92.6,69.5,174.5,3.032,17.0,21.0,12/21/2012,134.390975
Carrera Cabrio,Porsche,1.866,67.550,Passenger,74.970,3.4,300.0,92.6,69.5,174.5,3.075,17.0,23.0,7/11/2011,135.914710
Avalon,Toyota,63.849,18.140,Passenger,25.545,3.0,210.0,107.1,71.7,191.9,3.417,18.5,26.0,8/31/2011,84.911898
Land Cruiser,Toyota,9.835,34.080,Car,51.728,4.7,230.0,112.2,76.4,192.5,5.115,25.4,15.0,9/25/2011,102.528984
C70,Volvo,3.493,NaN,Passenger,45.500,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
S80,Volvo,18.969,NaN,Passenger,36.000,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

In [30]:
df[df["Horsepower"].between(200,220)]

,Manufacturer,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
Model,,,,,,,,,,,,,,,
RL,Acura,8.588,29.725,Passenger,42.000,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
A6,Audi,18.780,23.555,Passenger,33.950,2.8,200.0,108.7,76.1,192.0,3.561,18.5,22.0,8/9/2011,84.565105
Park Avenue,Buick,27.851,20.190,Passenger,31.965,3.8,205.0,113.8,74.7,206.8,3.778,18.5,24.0,3/23/2012,85.828408
LeSabre,Buick,83.257,13.360,Passenger,27.885,3.8,205.0,112.2,73.5,200.0,3.591,17.5,25.0,7/23/2011,84.254526
Catera,Cadillac,11.185,18.225,Passenger,31.010,3.0,200.0,107.4,70.3,194.8,3.770,18.0,22.0,9/28/2011,83.483094
Camaro,Chevrolet,26.402,13.025,Passenger,24.340,3.8,200.0,101.1,74.1,193.2,3.500,16.8,25.0,10/23/2011,81.118543
Concorde,Chrysler,31.148,13.725,Passenger,22.245,2.7,200.0,113.0,74.4,209.1,3.452,17.0,26.0,6/6/2012,80.023782
Intrepid,Dodge,88.028,12.275,Passenger,22.505,2.7,202.0,113.0,74.7,203.7,3.489,17.0,NaN,6/2/2012,80.831470
Crown Victoria,Ford,63.403,14.210,Passenger,22.195,4.6,200.0,114.7,78.2,212.0,3.908,19.0,21.0,9/26/2011,80.499537
Explorer,Ford,276.747,16.640,Car,31.930,4.0,210.0,111.6,70.2,190.7,3.876,21.0,19.0,4/25/2012,87.635496
F-Series,Ford,540.561,15.075,Car,26.935,4.6,220.0,138.5,79.1,224.5,4.241,25.1,18.0,8/16/2012,89.401935
Passport,Honda,12.855,17.525,Car,26.600,3.2,205.0,106.4,70.4,178.2,3.857,21.1,19.0,10/9/2012,83.602501
Odyssey,Honda,76.029,19.490,Car,26.000,3.5,210.0,118.1,75.6,201.2,4.288,20.0,23.0,2/8/2012,85.217691
ES300,Lexus,24.072,26.975,Passenger,31.505,3.0,210.0,105.1,70.5,190.2,3.373,18.5,23.0,7/9/2012,87.211001
RX300,Lexus,51.238,NaN,Car,34.605,3.0,220.0,103.0,71.5,180.1,3.900,17.2,21.0,1/4/2012,91.943802
Town car,Lincoln,48.911,21.725,Passenger,43.330,4.6,215.0,117.7,78.2,215.3,4.121,19.0,21.0,6/4/2012,93.957917
Diamante,Mitsubishi,5.711,16.575,Passenger,24.997,3.5,210.0,107.1,70.3,194.1,3.443,19.0,22.0,8/28/2012,84.830779
Montero,Mitsubishi,11.337,19.125,Car,31.807,3.5,200.0,107.3,69.9,186.6,4.520,24.3,18.0,1/17/2012,83.920815
Grand Marquis,Mercury,81.174,14.875,Passenger,22.605,4.6,200.0,114.7,78.2,212.0,3.958,19.0,21.0,7/24/2012,80.657696
Mountaineer,Mercury,27.609,20.430,Car,27.560,4.0,210.0,111.6,70.2,190.1,3.876,21.0,18.0,2/13/2008,85.949744
CLK Coupe,Mercedes-B,11.592,NaN,Passenger,41.600,3.2,215.0,105.9,67.8,180.3,3.213,16.4,26.0,7/8/2011,92.925792
M-Class,Mercedes-B,28.976,NaN,Car,35.300,3.2,215.0,111.0,72.2,180.6,4.387,19.0,20.0,2/10/2011,90.495532
Intrigue,Oldsmobile,38.554,NaN,Passenger,24.150,3.5,215.0,109.0,73.6,195.9,3.455,18.0,NaN,4/1/2011,86.272523
Firebird,Pontiac,19.911,17.805,Passenger,25.310,3.8,200.0,101.1,74.5,193.4,3.492,16.8,25.0,6/16/2012,81.492726
Bonneville,Pontiac,35.945,13.225,Passenger,23.755,3.8,205.0,112.2,72.6,202.5,3.590,17.5,24.0,5/18/2011,82.661356
Boxter,Porsche,8.982,41.250,Passenger,41.430,2.7,217.0,95.2,70.1,171.0,2.778,17.0,22.0,2/19/2012,93.437331
Avalon,Toyota,63.849,18.140,Passenger,25.545,3.0,210.0,107.1,71.7,191.9,3.417,18.5,26.0,8/31/2011,84.911898
S80,Volvo,18.969,NaN,Passenger,36.000,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

In [31]:
df["Vehicle_type"].value_counts()

Vehicle_type
Passenger    116
Car           41
Name: count, dtype: int64

In [32]:
df[df["Horsepower"].between(200,220)]["Vehicle_type"].value_counts()

Vehicle_type
Passenger    20
Car           8
Name: count, dtype: int64

In [33]:
df[df["Manufacturer"].isin(["Toyota","Honda"])]

,Manufacturer,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
Model,,,,,,,,,,,,,,,
Civic,Honda,199.685,9.850,Passenger,12.885,1.6,106.0,103.2,67.1,175.1,2.339,11.9,32.0,10/21/2011,42.879097
Accord,Honda,230.902,13.210,Passenger,15.350,2.3,135.0,106.9,70.3,188.8,2.932,17.1,27.0,5/20/2012,54.269548
CR-V,Honda,73.203,17.710,Car,20.550,2.0,146.0,103.2,68.9,177.6,3.219,15.3,24.0,3/21/2012,60.087967
Passport,Honda,12.855,17.525,Car,26.600,3.2,205.0,106.4,70.4,178.2,3.857,21.1,19.0,10/9/2012,83.602501
Odyssey,Honda,76.029,19.490,Car,26.000,3.5,210.0,118.1,75.6,201.2,4.288,20.0,23.0,2/8/2012,85.217691
Corolla,Toyota,142.535,10.025,Passenger,13.108,1.8,120.0,97.0,66.7,174.0,2.420,13.2,33.0,4/11/2011,47.968972
Camry,Toyota,247.994,13.245,Passenger,17.518,2.2,133.0,105.2,70.1,188.5,2.998,18.5,27.0,2/10/2011,54.372420
Avalon,Toyota,63.849,18.140,Passenger,25.545,3.0,210.0,107.1,71.7,191.9,3.417,18.5,26.0,8/31/2011,84.911898
Celica,Toyota,33.269,15.445,Passenger,16.875,1.8,140.0,102.4,68.3,170.5,2.425,14.5,31.0,12/29/2012,56.496030
Tacoma,Toyota,84.087,9.575,Car,11.528,2.4,142.0,103.3,66.5,178.7,2.580,15.1,23.0,8/1/2011,55.297117
Sienna,Toyota,65.119,NaN,Car,22.368,3.0,194.0,114.2,73.4,193.5,3.759,20.9,22.0,10/5/2012,78.027219
RAV4,Toyota,25.106,13.325,Car,16.888,2.0,127.0,94.9,66.7,163.8,2.668,15.3,27.0,5/6/2011,51.955109
4Runner,Toyota,68.411,19.425,Car,22.288,2.7,150.0,105.3,66.5,183.3,3.440,18.5,23.0,3/7/2011,62.355577
Land Cruiser,Toyota,9.835,34.080,Car,51.728,4.7,230.0,112.2,76.4,192.5,5.115,25.4,15.0,9/25/2011,102.528984

In [34]:
df[df["Manufacturer"].isin(["Toyota","Honda"])].loc[:,["Engine_size","Wheelbase"]]

              Engine_size  Wheelbase
Model
Civic                 1.6      103.2
Accord                2.3      106.9
CR-V                  2.0      103.2
Passport              3.2      106.4
Odyssey               3.5      118.1
Corolla               1.8       97.0
Camry                 2.2      105.2
Avalon                3.0      107.1
Celica                1.8      102.4
Tacoma                2.4      103.3
Sienna                3.0      114.2
RAV4                  2.0       94.9
4Runner               2.7      105.3
Land Cruiser          4.7      112.2

In [35]:
df[df["Manufacturer"].isin(["Toyota","Honda"])].value_counts("Manufacturer")

Manufacturer
Toyota    9
Honda     5
Name: count, dtype: int64

In [36]:
df[df["Manufacturer"].isin(["Toyota","Honda"])].value_counts()

Manufacturer  Sales_in_thousands  __year_resale_value  Vehicle_type  Price_in_thousands  Engine_size  Horsepower  Wheelbase  Width  Length  Curb_weight  Fuel_capacity  Fuel_efficiency  Latest_Launch  Power_perf_factor
Honda         12.855              17.525               Car           26.600              3.2          205.0       106.4      70.4   178.2   3.857        21.1           19.0             10/9/2012      83.602501            1
              73.203              17.710               Car           20.550              2.0          146.0       103.2      68.9   177.6   3.219        15.3           24.0             3/21/2012      60.087967            1
              76.029              19.490               Car           26.000              3.5          210.0       118.1      75.6   201.2   4.288        20.0           23.0             2/8/2012       85.217691            1
              199.685             9.850                Passenger     12.885              1.6          106.0       103.2      67.1   175.1   2.339        11.9           32.0             10/21/2011     42.879097            1
              230.902             13.210               Passenger     15.350              2.3          135.0       106.9      70.3   188.8   2.932        17.1           27.0             5/20/2012      54.269548            1
Toyota        9.835               34.080               Car           51.728              4.7          230.0       112.2      76.4   192.5   5.115        25.4           15.0             9/25/2011      102.528984           1
              25.106              13.325               Car           16.888              2.0          127.0       94.9       66.7   163.8   2.668        15.3           27.0             5/6/2011       51.955109            1
              33.269              15.445               Passenger     16.875              1.8          140.0       102.4      68.3   170.5   2.425        14.5           31.0             12/29/2012     56.496030            1
              63.849              18.140               Passenger     25.545              3.0          210.0       107.1      71.7   191.9   3.417        18.5           26.0             8/31/2011      84.911898            1
              68.411              19.425               Car           22.288              2.7          150.0       105.3      66.5   183.3   3.440        18.5           23.0             3/7/2011       62.355577            1
              84.087              9.575                Car           11.528              2.4          142.0       103.3      66.5   178.7   2.580        15.1           23.0             8/1/2011       55.297117            1
              142.535             10.025               Passenger     13.108              1.8          120.0       97.0       66.7   174.0   2.420        13.2           33.0             4/11/2011      47.968972            1
              247.994             13.245               Passenger     17.518              2.2          133.0       105.2      70.1   188.5   2.998        18.5           27.0             2/10/2011      54.372420            1
Name: count, dtype: int64

In [37]:
df.sort_values(by=["Manufacturer"],ascending=False)

,Manufacturer,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
Model,,,,,,,,,,,,,,,
S80,Volvo,18.969,NaN,Passenger,36.000,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655
C70,Volvo,3.493,NaN,Passenger,45.500,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
V70,Volvo,17.531,NaN,Passenger,28.800,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
S70,Volvo,15.245,NaN,Passenger,27.500,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
V40,Volvo,3.545,NaN,Passenger,24.400,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
S40,Volvo,16.957,NaN,Passenger,23.400,1.9,160.0,100.5,67.6,176.6,2.998,15.8,25.0,2/18/2011,66.113057
Beetle,Volkswagen,49.463,NaN,Passenger,15.900,2.0,115.0,98.9,67.9,161.1,2.769,14.5,26.0,10/20/2011,47.329632
GTI,Volkswagen,5.596,13.760,Passenger,17.500,2.0,115.0,98.9,68.3,163.3,2.762,14.6,26.0,4/1/2011,47.946841
Cabrio,Volkswagen,9.569,16.575,Passenger,19.990,2.0,115.0,97.4,66.7,160.4,3.079,13.7,26.0,5/31/2011,48.907372
Passat,Volkswagen,51.102,16.725,Passenger,21.200,1.8,150.0,106.4,68.5,184.1,3.043,16.4,27.0,10/30/2012,61.701381
Jetta,Volkswagen,83.721,13.240,Passenger,16.700,2.0,115.0,98.9,68.3,172.3,2.853,14.5,26.0,8/27/2011,47.638237
Golf,Volkswagen,9.761,11.425,Passenger,14.900,2.0,115.0,98.9,68.3,163.3,2.767,14.5,26.0,1/24/2011,46.943877
Tacoma,Toyota,84.087,9.575,Car,11.528,2.4,142.0,103.3,66.5,178.7,2.580,15.1,23.0,8/1/2011,55.297117
Corolla,Toyota,142.535,10.025,Passenger,13.108,1.8,120.0,97.0,66.7,174.0,2.420,13.2,33.0,4/11/2011,47.968972
Camry,Toyota,247.994,13.245,Passenger,17.518,2.2,133.0,105.2,70.1,188.5,2.998,18.5,27.0,2/10/2011,54.372420
Avalon,Toyota,63.849,18.140,Passenger,25.545,3.0,210.0,107.1,71.7,191.9,3.417,18.5,26.0,8/31/2011,84.911898
Celica,Toyota,33.269,15.445,Passenger,16.875,1.8,140.0,102.4,68.3,170.5,2.425,14.5,31.0,12/29/2012,56.496030
Sienna,Toyota,65.119,NaN,Car,22.368,3.0,194.0,114.2,73.4,193.5,3.759,20.9,22.0,10/5/2012,78.027219
RAV4,Toyota,25.106,13.325,Car,16.888,2.0,127.0,94.9,66.7,163.8,2.668,15.3,27.0,5/6/2011,51.955109
4Runner,Toyota,68.411,19.425,Car,22.288,2.7,150.0,105.3,66.5,183.3,3.440,18.5,23.0,3/7/2011,62.355577
Land Cruiser,Toyota,9.835,34.080,Car,51.728,4.7,230.0,112.2,76.4,192.5,5.115,25.4,15.0,9/25/2011,102.528984
Forester,Subaru,33.028,NaN,Car,20.095,2.5,165.0,99.4,68.3,175.2,3.125,15.9,24.0,9/10/2012,66.762943
Outback,Subaru,47.107,NaN,Passenger,22.695,2.5,165.0,103.5,67.5,185.8,3.415,16.9,25.0,7/7/2011,67.765908
SC,Saturn,24.546,10.590,Passenger,12.535,1.9,100.0,102.4,66.4,180.0,2.367,12.1,33.0,3/16/2011,40.700072
SL,Saturn,80.620,9.200,Passenger,10.685,1.9,100.0,102.4,66.4,176.9,2.332,12.1,33.0,8/16/2012,39.986425
SW,Saturn,5.223,10.790,Passenger,14.290,1.9,124.0,102.4,66.4,176.9,2.452,12.1,31.0,1/15/2011,49.865774
LW,Saturn,8.472,NaN,Passenger,18.835,2.2,137.0,106.5,69.0,190.4,3.075,13.1,27.0,8/5/2011,56.295243
LS,Saturn,49.989,NaN,Passenger,15.010,2.2,137.0,106.5,69.0,190.4,2.910,13.1,28.0,12/4/2012,54.819728
3-Sep,Saab,12.115,NaN,Passenger,26.100,2.0,185.0,102.6,67.4,182.2,2.990,16.9,23.0,6/12/2011,76.023048
5-Sep,Saab,9.191,NaN,Passenger,33.120,2.3,170.0,106.4,70.6,189.2,3.280,18.5,23.0,11/9/2012,73.503778
Carrera Cabrio,Porsche,1.866,67.550,Passenger,74.970,3.4,300.0,92.6,69.5,174.5,3.075,17.0,23.0,7/11/2011,135.914710
Carrera Coupe,Porsche,1.280,60.625,Passenger,71.020,3.4,300.0,92.6,69.5,174.5,3.032,17.0,21.0,12/21/2012,134.390975
Boxter,Porsche,8.982,41.250,Passenger,41.430,2.7,217.0,95.2,70.1,171.0,2.778,17.0,22.0,2/19/2012,93.437331
Grand Prix,Pontiac,92.364,14.010,Passenger,21.665,3.8,195.0,110.5,72.7,196.5,3.396,18.0,25.0,10/15/2012,78.318168
Grand Am,Pontiac,131.097,10.290,Passenger,19.720,3.4,175.0,107.0,70.4,186.3,3.091,15.2,25.0,11/26/2012,70.389737
Firebird,Pontiac,19.911,17.805,Passenger,25.310,3.8,200.0,101.1,74.5,193.4,3.492,16.8,25.0,6/16/2012,81.492726
Sunfire,Pontiac,51.645,13.790,Passenger,21.610,2.4,150.0,104.1,68.4,181.9,2.906,15.0,27.0,1/25/2012,62.015870
Bonneville,Pontiac,35.945,13.225,Passenger,23.755,3.8,205.0,112.2,72.6,202.5,3.590,17.5,24.0,5/18/2011,82.661356
Montana,Pontiac,39.572,NaN,Car,25.635,3.4,185.0,120.0,72.7,201.3,3.942,25.0,23.0,7/22/2012,76.208440
Prowler,Plymouth,1.872,NaN,Passenger,43.000,3.5,253.0,113.3,76.3,165.4,2.850,12.0,21.0,6/27/2012,106.984456
Voyager,Plymouth,24.155,12.025,Car,18.850,2.4,150.0,113.3,76.8,186.3,3.528,20.0,24.0,4/24/2011,60.951185
Breeze,Plymouth,5.240,9.800,Passenger,16.080,2.0,132.0,108.0,71.0,186.3,2.942,16.0,27.0,11/14/2011,53.411898
Neon,Plymouth,32.734,7.750,Passenger,12.640,2.0,132.0,105.0,74.4,174.4,2.559,12.5,29.0,4/26/2011,52.084899
Aurora,Oldsmobile,14.690,19.890,Passenger,36.229,4.0,250.0,113.8,74.4,205.4,3.967,18.5,22.0,2/18/2011,103.441693
Intrigue,Oldsmobile,38.554,NaN,Passenger,24.150,3.5,215.0,109.0,73.6,195.9,3.455,18.0,NaN,4/1/2011,86.272523
Alero,Oldsmobile,80.255,NaN,Passenger,18.270,2.4,150.0,107.0,70.1,186.7,2.958,15.0,27.0,10/20/2009,60.727447
Cutlass,Oldsmobile,1.112,11.240,Passenger,18.145,3.1,150.0,107.0,69.4,192.0,3.102,15.2,25.0,5/31/2011,60.861612
Bravada,Oldsmobile,20.017,19.925,Car,31.598,4.3,190.0,107.0,67.8,181.2,4.068,17.5,19.0,9/21/2011,80.511673
Silhouette,Oldsmobile,24.361,15.240,Car,25.345,3.4,185.0,120.0,72.2,201.4,3.948,25.0,22.0,6/25/2011,76.096570
Frontier,Nissan,65.005,NaN,Car,17.890,3.3,170.0,116.1,66.5,196.1,3.217,19.4,18.0,8/27/2011,67.889271
Xterra,Nissan,54.158,NaN,Car,22.799,3.3,170.0,104.3,70.4,178.0,3.821,19.4,18.0,1/24/2011,69.782944
Pathfinder,Nissan,42.574,17.810,Car,29.299,3.3,170.0,106.3,71.7,182.6,3.947,21.0,19.0,9/25/2011,72.290355
Quest,Nissan,27.308,15.380,Car,26.399,3.3,170.0,112.2,74.9,194.8,3.991,20.0,21.0,3/7/2011,71.171664
Maxima,Nissan,79.853,15.125,Passenger,26.249,3.0,222.0,108.3,70.3,190.5,3.294,18.5,25.0,5/6/2011,89.427820
Altima,Nissan,88.094,11.295,Passenger,20.390,2.4,155.0,103.1,69.1,183.5,3.012,15.9,25.0,8/2/2011,63.313728
Sentra,Nissan,42.643,8.450,Passenger,13.499,1.8,126.0,99.8,67.3,177.5,2.593,13.2,30.0,8/31/2011,50.241978
Montero Sport,Mitsubishi,39.348,13.880,Car,22.527,3.0,173.0,107.3,66.7,178.3,3.510,19.5,20.0,5/18/2012,70.660942
Galant,Mitsubishi,55.616,10.595,Passenger,17.357,2.4,145.0,103.7,68.5,187.8,2.945,16.3,25.0,1/29/2012,58.606773
Diamante,Mitsubishi,5.711,16.575,Passenger,24.997,3.5,210.0,107.1,70.3,194.1,3.443,19.0,22.0,8/28/2012,84.830779
3000GT,Mitsubishi,0.110,20.940,Passenger,25.450,3.0,161.0,97.2,72.4,180.3,3.131,19.8,21.0,6/29/2012,67.544155
Montero,Mitsubishi,11.337,19.125,Car,31.807,3.5,200.0,107.3,69.9,186.6,4.520,24.3,18.0,1/17/2012,83.920815
Eclipse,Mitsubishi,42.541,10.395,Passenger,19.047,2.4,154.0,100.8,68.9,175.4,2.910,15.9,24.0,11/24/2012,62.441962
Mirage,Mitsubishi,26.232,8.325,Passenger,13.987,1.8,113.0,98.4,66.5,173.6,2.250,13.2,30.0,4/23/2012,45.832181
Villager,Mercury,20.380,14.795,Car,22.510,3.3,170.0,112.2,74.9,194.7,3.944,20.0,21.0,10/20/2009,69.671461
Mountaineer,Mercury,27.609,20.430,Car,27.560,4.0,210.0,111.6,70.2,190.1,3.876,21.0,18.0,2/13/2008,85.949744
Grand Marquis,Mercury,81.174,14.875,Passenger,22.605,4.6,200.0,114.7,78.2,212.0,3.958,19.0,21.0,7/24/2012,80.657696
Sable,Mercury,67.956,11.030,Passenger,19.035,3.0,153.0,108.5,73.0,199.7,3.379,16.0,24.0,9/22/2012,62.239967
Cougar,Mercury,26.529,13.890,Passenger,16.540,2.0,125.0,106.4,69.6,185.0,2.892,16.0,30.0,2/23/2012,51.113474
Mystique,Mercury,14.351,8.800,Passenger,16.240,2.0,125.0,106.5,69.1,184.8,2.769,15.0,28.0,12/19/2012,50.997748
SL-Class,Mercedes-B,3.311,58.600,Passenger,82.600,5.0,302.0,99.0,71.3,177.1,4.125,21.1,20.0,3/17/2011,139.982294
S-Class,Mercedes-B,16.774,50.375,Passenger,69.700,4.3,275.0,121.5,73.1,203.1,4.133,23.2,21.0,6/13/2011,125.273876
E-Class,Mercedes-B,27.602,41.450,Passenger,49.900,3.2,221.0,111.5,70.8,189.4,3.823,21.1,25.0,7/12/2011,98.249737
C-Class,Mercedes-B,18.392,26.050,Passenger,31.750,2.3,185.0,105.9,67.7,177.4,3.250,16.4,26.0,4/24/2011,78.280731
SLK,Mercedes-B,7.998,NaN,Passenger,38.900,2.3,190.0,94.5,67.5,157.9,3.055,15.9,26.0,1/16/2011,82.807362
SLK230,Mercedes-B,1.526,NaN,Passenger,41.000,2.3,185.0,94.5,67.5,157.3,2.975,14.0,27.0,8/6/2011,81.848969
CLK Coupe,Mercedes-B,11.592,NaN,Passenger,41.600,3.2,215.0,105.9,67.8,180.3,3.213,16.4,26.0,7/8/2011,92.925792
CL500,Mercedes-B,0.954,NaN,Passenger,85.500,5.0,302.0,113.6,73.1,196.6,4.115,23.2,20.0,4/11/2011,141.100985
M-Class,Mercedes-B,28.976,NaN,Car,35.300,3.2,215.0,111.0,72.2,180.6,4.387,19.0,20.0,2/10/2011,90.495532
Navigator,Lincoln,22.925,NaN,Car,42.660,5.4,300.0,119.0,79.9,204.8,5.393,30.0,15.0,12/23/2012,123.972047
Town car,Lincoln,48.911,21.725,Passenger,43.330,4.6,215.0,117.7,78.2,215.3,4.121,19.0,21.0,6/4/2012,93.957917
Continental,Lincoln,13.798,20.525,Passenger,39.080,4.6,275.0,109.0,73.6,208.5,3.868,20.0,22.0,8/3/2012,113.540207
RX300,Lexus,51.238,NaN,Car,34.605,3.0,220.0,103.0,71.5,180.1,3.900,17.2,21.0,1/4/2012,91.943802
LX470,Lexus,9.126,NaN,Car,60.105,4.7,230.0,112.2,76.4,192.5,5.401,25.4,15.0,10/30/2012,105.760458
LS400,Lexus,6.375,40.375,Passenger,54.005,4.0,290.0,112.2,72.0,196.7,3.890,22.5,22.0,3/29/2012,124.446716
GS400,Lexus,3.334,NaN,Passenger,46.305,4.0,300.0,110.2,70.9,189.2,3.693,19.8,21.0,11/28/2012,125.013357
GS300,Lexus,12.698,32.075,Passenger,37.805,3.0,225.0,110.2,70.9,189.2,3.638,19.8,23.0,5/10/2012,94.946698
ES300,Lexus,24.072,26.975,Passenger,31.505,3.0,210.0,105.1,70.5,190.2,3.373,18.5,23.0,7/9/2012,87.211001
Cherokee,Jeep,80.556,13.775,Car,21.620,4.0,190.0,101.4,69.4,167.5,3.194,20.0,20.0,10/5/2012,76.584440
Wrangler,Jeep,55.557,13.475,Car,14.460,2.5,120.0,93.4,66.7,152.0,3.045,19.0,17.0,3/4/2012,48.672898
Grand Cherokee,Jeep,157.040,18.810,Car,26.895,4.0,195.0,105.9,72.3,181.5,3.880,20.5,19.0,12/10/2011,80.387779
S-Type,Jaguar,15.467,NaN,Passenger,42.800,3.0,240.0,114.5,71.6,191.3,3.650,18.4,21.0,11/3/2012,102.178985
I30,Infiniti,23.713,19.690,Passenger,29.465,3.0,227.0,108.3,70.2,193.7,3.342,18.5,25.0,4/15/2012,92.436889
Sonata,Hyundai,29.450,8.910,Passenger,14.999,2.4,148.0,106.3,71.6,185.4,3.072,17.2,25.0,6/14/2012,58.758249
Elantra,Hyundai,66.692,7.825,Passenger,11.799,2.0,140.0,100.4,66.9,174.0,2.626,14.5,27.0,11/15/2011,54.590045
Accent,Hyundai,41.184,5.860,Passenger,9.699,1.5,92.0,96.1,65.7,166.7,2.240,11.9,31.0,9/10/2012,36.672284
Accord,Honda,230.902,13.210,Passenger,15.350,2.3,135.0,106.9,70.3,188.8,2.932,17.1,27.0,5/20/2012,54.269548
Civic,Honda,199.685,9.850,Passenger,12.885,1.6,106.0,103.2,67.1,175.1,2.339,11.9,32.0,10/21/2011,42.879097
CR-V,Honda,73.203,17.710,Car,20.550,2.0,146.0,103.2,68.9,177.6,3.219,15.3,24.0,3/21/2012,60.087967
Odyssey,Honda,76.029,19.490,Car,26.000,3.5,210.0,118.1,75.6,201.2,4.288,20.0,23.0,2/8/2012,85.217691
Passport,Honda,12.855,17.525,Car,26.600,3.2,205.0,106.4,70.4,178.2,3.857,21.1,19.0,10/9/2012,83.602501
Focus,Ford,175.670,NaN,Passenger,12.315,2.0,107.0,103.0,66.9,174.8,2.564,13.2,30.0,7/22/2012,43.117132
F-Series,Ford,540.561,15.075,Car,26.935,4.6,220.0,138.5,79.1,224.5,4.241,25.1,18.0,8/16/2012,89.401935
Ranger,Ford,220.650,7.850,Car,12.050,2.5,119.0,117.5,69.4,200.7,3.086,20.0,23.0,1/14/2012,47.389531
Expedition,Ford,125.338,23.575,Car,36.135,4.6,240.0,119.0,78.7,204.6,4.808,26.0,16.0,9/14/2012,100.024802
Windstar,Ford,155.787,13.175,Car,21.410,3.0,150.0,120.7,76.6,200.9,3.761,26.0,21.0,2/25/2012,62.095048
Explorer,Ford,276.747,16.640,Car,31.930,4.0,210.0,111.6,70.2,190.7,3.876,21.0,19.0,4/25/2012,87.635496
Crown Victoria,Ford,63.403,14.210,Passenger,22.195,4.6,200.0,114.7,78.2,212.0,3.908,19.0,21.0,9/26/2011,80.499537
Taurus,Ford,245.815,10.055,Passenger,17.885,3.0,155.0,108.5,73.0,197.6,3.368,16.0,24.0,12/20/2011,62.503740
Contour,Ford,35.068,8.835,Passenger,17.035,2.5,170.0,106.5,69.1,184.6,2.769,15.0,25.0,8/20/2012,67.351011
Mustang,Ford,113.369,12.760,Passenger,21.560,3.8,190.0,101.3,73.1,183.2,3.203,15.7,24.0,1/31/2012,76.509185
Escort,Ford,70.227,7.425,Passenger,12.070,2.0,110.0,98.4,67.0,174.7,2.468,12.7,30.0,3/31/2012,44.083709
Stratus,Dodge,71.186,10.185,Passenger,20.230,2.5,168.0,108.0,71.0,186.0,3.058,16.0,24.0,10/31/2011,67.876108
Intrepid,Dodge,88.028,12.275,Passenger,22.505,2.7,202.0,113.0,74.7,203.7,3.489,17.0,NaN,6/2/2012,80.831470
Ram Pickup,Dodge,227.061,15.060,Car,19.460,5.2,230.0,138.7,79.3,224.2,4.470,26.0,17.0,3/6/2012,90.211700
Avenger,Dodge,4.734,12.545,Passenger,19.045,2.5,163.0,103.7,69.1,190.2,2.879,15.9,24.0,7/1/2012,65.650508
Neon,Dodge,76.034,7.750,Passenger,12.640,2.0,132.0,105.0,74.4,174.4,2.567,12.5,29.0,12/12/2011,52.084899
Viper,Dodge,0.916,58.470,Passenger,69.725,8.0,450.0,96.2,75.7,176.7,3.375,19.0,16.0,8/7/2011,188.144323
Ram Wagon,Dodge,16.767,15.510,Car,21.315,3.9,175.0,109.6,78.8,192.6,4.245,32.0,15.0,1/6/2012,71.135292
Dakota,Dodge,111.313,11.260,Car,16.980,2.5,120.0,131.0,71.5,215.0,3.557,22.0,19.0,11/25/2011,49.645002
Durango,Dodge,101.323,NaN,Car,26.310,5.2,230.0,115.7,71.7,193.5,4.394,25.0,17.0,6/27/2012,92.854125
Caravan,Dodge,181.749,12.025,Car,19.565,2.4,150.0,113.3,76.8,186.3,3.533,20.0,24.0,9/1/2011,61.227000
Ram Van,Dodge,31.038,13.425,Car,18.575,3.9,175.0,127.2,78.8,208.5,4.298,32.0,16.0,7/26/2012,70.078322
300M,Chrysler,30.696,NaN,Passenger,29.185,3.5,253.0,113.0,74.4,197.8,3.567,17.0,23.0,2/10/2012,101.655244
Town & Country,Chrysler,53.480,19.540,Car,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7/13/2011,NaN
LHS,Chrysler,13.462,17.325,Passenger,28.340,3.5,253.0,113.0,74.4,207.7,3.564,17.0,23.0,5/8/2012,101.329281
Cirrus,Chrysler,32.306,12.640,Passenger,16.480,2.0,132.0,108.0,71.0,186.0,2.911,16.0,27.0,10/6/2011,53.566200
Concorde,Chrysler,31.148,13.725,Passenger,22.245,2.7,200.0,113.0,74.4,209.1,3.452,17.0,26.0,6/6/2012,80.023782
Sebring Conv.,Chrysler,32.775,14.180,Passenger,24.495,2.5,168.0,106.0,69.2,193.0,3.332,16.0,24.0,11/17/2011,69.521355
Sebring Coupe,Chrysler,7.854,12.360,Passenger,19.840,2.5,163.0,103.7,69.7,190.9,2.967,15.9,24.0,1/16/2012,65.957184
Lumina,Chevrolet,24.629,10.310,Passenger,18.890,3.1,175.0,107.5,72.5,200.9,3.330,16.6,25.0,5/24/2011,69.991396
Monte Carlo,Chevrolet,42.593,11.525,Passenger,19.390,3.4,180.0,110.5,72.7,197.9,3.340,17.0,27.0,12/22/2011,72.030917
Cavalier,Chevrolet,145.519,9.250,Passenger,13.260,2.2,115.0,104.1,67.9,180.9,2.676,14.3,27.0,8/17/2011,46.363347
Malibu,Chevrolet,135.126,11.225,Passenger,16.535,3.1,170.0,107.0,69.4,190.4,3.051,15.0,25.0,3/19/2012,67.314462
Camaro,Chevrolet,26.402,13.025,Passenger,24.340,3.8,200.0,101.1,74.1,193.2,3.500,16.8,25.0,10/23/2011,81.118543
Prizm,Chevrolet,32.299,9.125,Passenger,13.960,1.8,120.0,97.1,66.7,174.3,2.398,13.2,33.0,9/11/2011,48.297636
Metro,Chevrolet,21.855,5.160,Passenger,9.235,1.0,55.0,93.1,62.6,149.4,1.895,10.3,45.0,4/13/2012,23.276272
Impala,Chevrolet,107.995,NaN,Passenger,18.890,3.4,180.0,110.5,73.0,200.0,3.389,17.0,27.0,6/18/2011,71.838039
Corvette,Chevrolet,17.947,36.225,Passenger,45.705,5.7,345.0,104.5,73.6,179.7,3.210,19.1,22.0,5/12/2012,141.141150
Seville,Cadillac,15.943,27.100,Passenger,44.475,4.6,275.0,112.2,75.0,201.0,NaN,18.5,22.0,4/29/2011,115.621358
Escalade,Cadillac,14.785,NaN,Car,46.225,5.7,255.0,117.5,77.0,201.2,5.572,30.0,15.0,4/17/2012,109.509117
Catera,Cadillac,11.185,18.225,Passenger,31.010,3.0,200.0,107.4,70.3,194.8,3.770,18.0,22.0,9/28/2011,83.483094
Eldorado,Cadillac,6.536,25.725,Passenger,39.665,4.6,275.0,108.0,75.5,200.6,3.843,19.0,22.0,11/27/2011,113.765874
DeVille,Cadillac,63.729,22.525,Passenger,39.895,4.6,275.0,115.3,74.5,207.2,3.978,18.5,22.0,2/23/2012,113.854598
LeSabre,Buick,83.257,13.360,Passenger,27.885,3.8,205.0,112.2,73.5,200.0,3.591,17.5,25.0,7/23/2011,84.254526
Park Avenue,Buick,27.851,20.190,Passenger,31.965,3.8,205.0,113.8,74.7,206.8,3.778,18.5,24.0,3/23/2012,85.828408
Regal,Buick,39.350,13.740,Passenger,25.300,3.8,240.0,109.0,72.7,196.2,3.543,17.5,23.0,9/3/2011,95.636703
Century,Buick,91.561,12.475,Passenger,21.975,3.1,175.0,109.0,72.7,194.6,3.368,17.5,25.0,11/2/2011,71.181451
328i,BMW,9.231,28.675,Passenger,33.400,2.8,193.0,107.3,68.5,176.0,3.197,16.6,24.0,1/29/2012,81.877069
323i,BMW,19.747,NaN,Passenger,26.990,2.5,170.0,107.3,68.4,176.0,3.179,16.6,26.0,6/28/2011,71.191207
528i,BMW,17.527,36.125,Passenger,38.900,2.8,193.0,111.4,70.9,188.0,3.472,18.5,25.0,4/4/2011,83.998724
A6,Audi,18.780,23.555,Passenger,33.950,2.8,200.0,108.7,76.1,192.0,3.561,18.5,22.0,8/9/2011,84.565105
A4,Audi,20.397,22.255,Passenger,23.990,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
A8,Audi,1.380,39.000,Passenger,62.000,4.2,310.0,113.0,74.0,198.2,3.902,23.7,21.0,2/27/2012,134.656858
CL,Acura,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
TL,Acura,39.384,19.875,Passenger,28.400,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
RL,Acura,8.588,29.725,Passenger,42.000,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
Integra,Acura,16.919,16.360,Passenger,21.500,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150

In [38]:
df.sort_values(by=["Manufacturer","Vehicle_type","Horsepower","Price_in_thousands"],ascending=[False,True,False,True])

,Manufacturer,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
Model,,,,,,,,,,,,,,,
C70,Volvo,3.493,NaN,Passenger,45.500,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
S80,Volvo,18.969,NaN,Passenger,36.000,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655
S70,Volvo,15.245,NaN,Passenger,27.500,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
V70,Volvo,17.531,NaN,Passenger,28.800,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
S40,Volvo,16.957,NaN,Passenger,23.400,1.9,160.0,100.5,67.6,176.6,2.998,15.8,25.0,2/18/2011,66.113057
V40,Volvo,3.545,NaN,Passenger,24.400,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
Passat,Volkswagen,51.102,16.725,Passenger,21.200,1.8,150.0,106.4,68.5,184.1,3.043,16.4,27.0,10/30/2012,61.701381
Golf,Volkswagen,9.761,11.425,Passenger,14.900,2.0,115.0,98.9,68.3,163.3,2.767,14.5,26.0,1/24/2011,46.943877
Beetle,Volkswagen,49.463,NaN,Passenger,15.900,2.0,115.0,98.9,67.9,161.1,2.769,14.5,26.0,10/20/2011,47.329632
Jetta,Volkswagen,83.721,13.240,Passenger,16.700,2.0,115.0,98.9,68.3,172.3,2.853,14.5,26.0,8/27/2011,47.638237
GTI,Volkswagen,5.596,13.760,Passenger,17.500,2.0,115.0,98.9,68.3,163.3,2.762,14.6,26.0,4/1/2011,47.946841
Cabrio,Volkswagen,9.569,16.575,Passenger,19.990,2.0,115.0,97.4,66.7,160.4,3.079,13.7,26.0,5/31/2011,48.907372
Land Cruiser,Toyota,9.835,34.080,Car,51.728,4.7,230.0,112.2,76.4,192.5,5.115,25.4,15.0,9/25/2011,102.528984
Sienna,Toyota,65.119,NaN,Car,22.368,3.0,194.0,114.2,73.4,193.5,3.759,20.9,22.0,10/5/2012,78.027219
4Runner,Toyota,68.411,19.425,Car,22.288,2.7,150.0,105.3,66.5,183.3,3.440,18.5,23.0,3/7/2011,62.355577
Tacoma,Toyota,84.087,9.575,Car,11.528,2.4,142.0,103.3,66.5,178.7,2.580,15.1,23.0,8/1/2011,55.297117
RAV4,Toyota,25.106,13.325,Car,16.888,2.0,127.0,94.9,66.7,163.8,2.668,15.3,27.0,5/6/2011,51.955109
Avalon,Toyota,63.849,18.140,Passenger,25.545,3.0,210.0,107.1,71.7,191.9,3.417,18.5,26.0,8/31/2011,84.911898
Celica,Toyota,33.269,15.445,Passenger,16.875,1.8,140.0,102.4,68.3,170.5,2.425,14.5,31.0,12/29/2012,56.496030
Camry,Toyota,247.994,13.245,Passenger,17.518,2.2,133.0,105.2,70.1,188.5,2.998,18.5,27.0,2/10/2011,54.372420
Corolla,Toyota,142.535,10.025,Passenger,13.108,1.8,120.0,97.0,66.7,174.0,2.420,13.2,33.0,4/11/2011,47.968972
Forester,Subaru,33.028,NaN,Car,20.095,2.5,165.0,99.4,68.3,175.2,3.125,15.9,24.0,9/10/2012,66.762943
Outback,Subaru,47.107,NaN,Passenger,22.695,2.5,165.0,103.5,67.5,185.8,3.415,16.9,25.0,7/7/2011,67.765908
LS,Saturn,49.989,NaN,Passenger,15.010,2.2,137.0,106.5,69.0,190.4,2.910,13.1,28.0,12/4/2012,54.819728
LW,Saturn,8.472,NaN,Passenger,18.835,2.2,137.0,106.5,69.0,190.4,3.075,13.1,27.0,8/5/2011,56.295243
SW,Saturn,5.223,10.790,Passenger,14.290,1.9,124.0,102.4,66.4,176.9,2.452,12.1,31.0,1/15/2011,49.865774
SL,Saturn,80.620,9.200,Passenger,10.685,1.9,100.0,102.4,66.4,176.9,2.332,12.1,33.0,8/16/2012,39.986425
SC,Saturn,24.546,10.590,Passenger,12.535,1.9,100.0,102.4,66.4,180.0,2.367,12.1,33.0,3/16/2011,40.700072
3-Sep,Saab,12.115,NaN,Passenger,26.100,2.0,185.0,102.6,67.4,182.2,2.990,16.9,23.0,6/12/2011,76.023048
5-Sep,Saab,9.191,NaN,Passenger,33.120,2.3,170.0,106.4,70.6,189.2,3.280,18.5,23.0,11/9/2012,73.503778
Carrera Coupe,Porsche,1.280,60.625,Passenger,71.020,3.4,300.0,92.6,69.5,174.5,3.032,17.0,21.0,12/21/2012,134.390975
Carrera Cabrio,Porsche,1.866,67.550,Passenger,74.970,3.4,300.0,92.6,69.5,174.5,3.075,17.0,23.0,7/11/2011,135.914710
Boxter,Porsche,8.982,41.250,Passenger,41.430,2.7,217.0,95.2,70.1,171.0,2.778,17.0,22.0,2/19/2012,93.437331
Montana,Pontiac,39.572,NaN,Car,25.635,3.4,185.0,120.0,72.7,201.3,3.942,25.0,23.0,7/22/2012,76.208440
Bonneville,Pontiac,35.945,13.225,Passenger,23.755,3.8,205.0,112.2,72.6,202.5,3.590,17.5,24.0,5/18/2011,82.661356
Firebird,Pontiac,19.911,17.805,Passenger,25.310,3.8,200.0,101.1,74.5,193.4,3.492,16.8,25.0,6/16/2012,81.492726
Grand Prix,Pontiac,92.364,14.010,Passenger,21.665,3.8,195.0,110.5,72.7,196.5,3.396,18.0,25.0,10/15/2012,78.318168
Grand Am,Pontiac,131.097,10.290,Passenger,19.720,3.4,175.0,107.0,70.4,186.3,3.091,15.2,25.0,11/26/2012,70.389737
Sunfire,Pontiac,51.645,13.790,Passenger,21.610,2.4,150.0,104.1,68.4,181.9,2.906,15.0,27.0,1/25/2012,62.015870
Voyager,Plymouth,24.155,12.025,Car,18.850,2.4,150.0,113.3,76.8,186.3,3.528,20.0,24.0,4/24/2011,60.951185
Prowler,Plymouth,1.872,NaN,Passenger,43.000,3.5,253.0,113.3,76.3,165.4,2.850,12.0,21.0,6/27/2012,106.984456
Neon,Plymouth,32.734,7.750,Passenger,12.640,2.0,132.0,105.0,74.4,174.4,2.559,12.5,29.0,4/26/2011,52.084899
Breeze,Plymouth,5.240,9.800,Passenger,16.080,2.0,132.0,108.0,71.0,186.3,2.942,16.0,27.0,11/14/2011,53.411898
Bravada,Oldsmobile,20.017,19.925,Car,31.598,4.3,190.0,107.0,67.8,181.2,4.068,17.5,19.0,9/21/2011,80.511673
Silhouette,Oldsmobile,24.361,15.240,Car,25.345,3.4,185.0,120.0,72.2,201.4,3.948,25.0,22.0,6/25/2011,76.096570
Aurora,Oldsmobile,14.690,19.890,Passenger,36.229,4.0,250.0,113.8,74.4,205.4,3.967,18.5,22.0,2/18/2011,103.441693
Intrigue,Oldsmobile,38.554,NaN,Passenger,24.150,3.5,215.0,109.0,73.6,195.9,3.455,18.0,NaN,4/1/2011,86.272523
Cutlass,Oldsmobile,1.112,11.240,Passenger,18.145,3.1,150.0,107.0,69.4,192.0,3.102,15.2,25.0,5/31/2011,60.861612
Alero,Oldsmobile,80.255,NaN,Passenger,18.270,2.4,150.0,107.0,70.1,186.7,2.958,15.0,27.0,10/20/2009,60.727447
Frontier,Nissan,65.005,NaN,Car,17.890,3.3,170.0,116.1,66.5,196.1,3.217,19.4,18.0,8/27/2011,67.889271
Xterra,Nissan,54.158,NaN,Car,22.799,3.3,170.0,104.3,70.4,178.0,3.821,19.4,18.0,1/24/2011,69.782944
Quest,Nissan,27.308,15.380,Car,26.399,3.3,170.0,112.2,74.9,194.8,3.991,20.0,21.0,3/7/2011,71.171664
Pathfinder,Nissan,42.574,17.810,Car,29.299,3.3,170.0,106.3,71.7,182.6,3.947,21.0,19.0,9/25/2011,72.290355
Maxima,Nissan,79.853,15.125,Passenger,26.249,3.0,222.0,108.3,70.3,190.5,3.294,18.5,25.0,5/6/2011,89.427820
Altima,Nissan,88.094,11.295,Passenger,20.390,2.4,155.0,103.1,69.1,183.5,3.012,15.9,25.0,8/2/2011,63.313728
Sentra,Nissan,42.643,8.450,Passenger,13.499,1.8,126.0,99.8,67.3,177.5,2.593,13.2,30.0,8/31/2011,50.241978
Montero,Mitsubishi,11.337,19.125,Car,31.807,3.5,200.0,107.3,69.9,186.6,4.520,24.3,18.0,1/17/2012,83.920815
Montero Sport,Mitsubishi,39.348,13.880,Car,22.527,3.0,173.0,107.3,66.7,178.3,3.510,19.5,20.0,5/18/2012,70.660942
Diamante,Mitsubishi,5.711,16.575,Passenger,24.997,3.5,210.0,107.1,70.3,194.1,3.443,19.0,22.0,8/28/2012,84.830779
3000GT,Mitsubishi,0.110,20.940,Passenger,25.450,3.0,161.0,97.2,72.4,180.3,3.131,19.8,21.0,6/29/2012,67.544155
Eclipse,Mitsubishi,42.541,10.395,Passenger,19.047,2.4,154.0,100.8,68.9,175.4,2.910,15.9,24.0,11/24/2012,62.441962
Galant,Mitsubishi,55.616,10.595,Passenger,17.357,2.4,145.0,103.7,68.5,187.8,2.945,16.3,25.0,1/29/2012,58.606773
Mirage,Mitsubishi,26.232,8.325,Passenger,13.987,1.8,113.0,98.4,66.5,173.6,2.250,13.2,30.0,4/23/2012,45.832181
Mountaineer,Mercury,27.609,20.430,Car,27.560,4.0,210.0,111.6,70.2,190.1,3.876,21.0,18.0,2/13/2008,85.949744
Villager,Mercury,20.380,14.795,Car,22.510,3.3,170.0,112.2,74.9,194.7,3.944,20.0,21.0,10/20/2009,69.671461
Grand Marquis,Mercury,81.174,14.875,Passenger,22.605,4.6,200.0,114.7,78.2,212.0,3.958,19.0,21.0,7/24/2012,80.657696
Sable,Mercury,67.956,11.030,Passenger,19.035,3.0,153.0,108.5,73.0,199.7,3.379,16.0,24.0,9/22/2012,62.239967
Mystique,Mercury,14.351,8.800,Passenger,16.240,2.0,125.0,106.5,69.1,184.8,2.769,15.0,28.0,12/19/2012,50.997748
Cougar,Mercury,26.529,13.890,Passenger,16.540,2.0,125.0,106.4,69.6,185.0,2.892,16.0,30.0,2/23/2012,51.113474
M-Class,Mercedes-B,28.976,NaN,Car,35.300,3.2,215.0,111.0,72.2,180.6,4.387,19.0,20.0,2/10/2011,90.495532
SL-Class,Mercedes-B,3.311,58.600,Passenger,82.600,5.0,302.0,99.0,71.3,177.1,4.125,21.1,20.0,3/17/2011,139.982294
CL500,Mercedes-B,0.954,NaN,Passenger,85.500,5.0,302.0,113.6,73.1,196.6,4.115,23.2,20.0,4/11/2011,141.100985
S-Class,Mercedes-B,16.774,50.375,Passenger,69.700,4.3,275.0,121.5,73.1,203.1,4.133,23.2,21.0,6/13/2011,125.273876
E-Class,Mercedes-B,27.602,41.450,Passenger,49.900,3.2,221.0,111.5,70.8,189.4,3.823,21.1,25.0,7/12/2011,98.249737
CLK Coupe,Mercedes-B,11.592,NaN,Passenger,41.600,3.2,215.0,105.9,67.8,180.3,3.213,16.4,26.0,7/8/2011,92.925792
SLK,Mercedes-B,7.998,NaN,Passenger,38.900,2.3,190.0,94.5,67.5,157.9,3.055,15.9,26.0,1/16/2011,82.807362
C-Class,Mercedes-B,18.392,26.050,Passenger,31.750,2.3,185.0,105.9,67.7,177.4,3.250,16.4,26.0,4/24/2011,78.280731
SLK230,Mercedes-B,1.526,NaN,Passenger,41.000,2.3,185.0,94.5,67.5,157.3,2.975,14.0,27.0,8/6/2011,81.848969
Navigator,Lincoln,22.925,NaN,Car,42.660,5.4,300.0,119.0,79.9,204.8,5.393,30.0,15.0,12/23/2012,123.972047
Continental,Lincoln,13.798,20.525,Passenger,39.080,4.6,275.0,109.0,73.6,208.5,3.868,20.0,22.0,8/3/2012,113.540207
Town car,Lincoln,48.911,21.725,Passenger,43.330,4.6,215.0,117.7,78.2,215.3,4.121,19.0,21.0,6/4/2012,93.957917
LX470,Lexus,9.126,NaN,Car,60.105,4.7,230.0,112.2,76.4,192.5,5.401,25.4,15.0,10/30/2012,105.760458
RX300,Lexus,51.238,NaN,Car,34.605,3.0,220.0,103.0,71.5,180.1,3.900,17.2,21.0,1/4/2012,91.943802
GS400,Lexus,3.334,NaN,Passenger,46.305,4.0,300.0,110.2,70.9,189.2,3.693,19.8,21.0,11/28/2012,125.013357
LS400,Lexus,6.375,40.375,Passenger,54.005,4.0,290.0,112.2,72.0,196.7,3.890,22.5,22.0,3/29/2012,124.446716
GS300,Lexus,12.698,32.075,Passenger,37.805,3.0,225.0,110.2,70.9,189.2,3.638,19.8,23.0,5/10/2012,94.946698
ES300,Lexus,24.072,26.975,Passenger,31.505,3.0,210.0,105.1,70.5,190.2,3.373,18.5,23.0,7/9/2012,87.211001
Grand Cherokee,Jeep,157.040,18.810,Car,26.895,4.0,195.0,105.9,72.3,181.5,3.880,20.5,19.0,12/10/2011,80.387779
Cherokee,Jeep,80.556,13.775,Car,21.620,4.0,190.0,101.4,69.4,167.5,3.194,20.0,20.0,10/5/2012,76.584440
Wrangler,Jeep,55.557,13.475,Car,14.460,2.5,120.0,93.4,66.7,152.0,3.045,19.0,17.0,3/4/2012,48.672898
S-Type,Jaguar,15.467,NaN,Passenger,42.800,3.0,240.0,114.5,71.6,191.3,3.650,18.4,21.0,11/3/2012,102.178985
I30,Infiniti,23.713,19.690,Passenger,29.465,3.0,227.0,108.3,70.2,193.7,3.342,18.5,25.0,4/15/2012,92.436889
Sonata,Hyundai,29.450,8.910,Passenger,14.999,2.4,148.0,106.3,71.6,185.4,3.072,17.2,25.0,6/14/2012,58.758249
Elantra,Hyundai,66.692,7.825,Passenger,11.799,2.0,140.0,100.4,66.9,174.0,2.626,14.5,27.0,11/15/2011,54.590045
Accent,Hyundai,41.184,5.860,Passenger,9.699,1.5,92.0,96.1,65.7,166.7,2.240,11.9,31.0,9/10/2012,36.672284
Odyssey,Honda,76.029,19.490,Car,26.000,3.5,210.0,118.1,75.6,201.2,4.288,20.0,23.0,2/8/2012,85.217691
Passport,Honda,12.855,17.525,Car,26.600,3.2,205.0,106.4,70.4,178.2,3.857,21.1,19.0,10/9/2012,83.602501
CR-V,Honda,73.203,17.710,Car,20.550,2.0,146.0,103.2,68.9,177.6,3.219,15.3,24.0,3/21/2012,60.087967
Accord,Honda,230.902,13.210,Passenger,15.350,2.3,135.0,106.9,70.3,188.8,2.932,17.1,27.0,5/20/2012,54.269548
Civic,Honda,199.685,9.850,Passenger,12.885,1.6,106.0,103.2,67.1,175.1,2.339,11.9,32.0,10/21/2011,42.879097
Expedition,Ford,125.338,23.575,Car,36.135,4.6,240.0,119.0,78.7,204.6,4.808,26.0,16.0,9/14/2012,100.024802
F-Series,Ford,540.561,15.075,Car,26.935,4.6,220.0,138.5,79.1,224.5,4.241,25.1,18.0,8/16/2012,89.401935
Explorer,Ford,276.747,16.640,Car,31.930,4.0,210.0,111.6,70.2,190.7,3.876,21.0,19.0,4/25/2012,87.635496
Windstar,Ford,155.787,13.175,Car,21.410,3.0,150.0,120.7,76.6,200.9,3.761,26.0,21.0,2/25/2012,62.095048
Ranger,Ford,220.650,7.850,Car,12.050,2.5,119.0,117.5,69.4,200.7,3.086,20.0,23.0,1/14/2012,47.389531
Crown Victoria,Ford,63.403,14.210,Passenger,22.195,4.6,200.0,114.7,78.2,212.0,3.908,19.0,21.0,9/26/2011,80.499537
Mustang,Ford,113.369,12.760,Passenger,21.560,3.8,190.0,101.3,73.1,183.2,3.203,15.7,24.0,1/31/2012,76.509185
Contour,Ford,35.068,8.835,Passenger,17.035,2.5,170.0,106.5,69.1,184.6,2.769,15.0,25.0,8/20/2012,67.351011
Taurus,Ford,245.815,10.055,Passenger,17.885,3.0,155.0,108.5,73.0,197.6,3.368,16.0,24.0,12/20/2011,62.503740
Escort,Ford,70.227,7.425,Passenger,12.070,2.0,110.0,98.4,67.0,174.7,2.468,12.7,30.0,3/31/2012,44.083709
Focus,Ford,175.670,NaN,Passenger,12.315,2.0,107.0,103.0,66.9,174.8,2.564,13.2,30.0,7/22/2012,43.117132
Ram Pickup,Dodge,227.061,15.060,Car,19.460,5.2,230.0,138.7,79.3,224.2,4.470,26.0,17.0,3/6/2012,90.211700
Durango,Dodge,101.323,NaN,Car,26.310,5.2,230.0,115.7,71.7,193.5,4.394,25.0,17.0,6/27/2012,92.854125
Ram Van,Dodge,31.038,13.425,Car,18.575,3.9,175.0,127.2,78.8,208.5,4.298,32.0,16.0,7/26/2012,70.078322
Ram Wagon,Dodge,16.767,15.510,Car,21.315,3.9,175.0,109.6,78.8,192.6,4.245,32.0,15.0,1/6/2012,71.135292
Caravan,Dodge,181.749,12.025,Car,19.565,2.4,150.0,113.3,76.8,186.3,3.533,20.0,24.0,9/1/2011,61.227000
Dakota,Dodge,111.313,11.260,Car,16.980,2.5,120.0,131.0,71.5,215.0,3.557,22.0,19.0,11/25/2011,49.645002
Viper,Dodge,0.916,58.470,Passenger,69.725,8.0,450.0,96.2,75.7,176.7,3.375,19.0,16.0,8/7/2011,188.144323
Intrepid,Dodge,88.028,12.275,Passenger,22.505,2.7,202.0,113.0,74.7,203.7,3.489,17.0,NaN,6/2/2012,80.831470
Stratus,Dodge,71.186,10.185,Passenger,20.230,2.5,168.0,108.0,71.0,186.0,3.058,16.0,24.0,10/31/2011,67.876108
Avenger,Dodge,4.734,12.545,Passenger,19.045,2.5,163.0,103.7,69.1,190.2,2.879,15.9,24.0,7/1/2012,65.650508
Neon,Dodge,76.034,7.750,Passenger,12.640,2.0,132.0,105.0,74.4,174.4,2.567,12.5,29.0,12/12/2011,52.084899
Town & Country,Chrysler,53.480,19.540,Car,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7/13/2011,NaN
LHS,Chrysler,13.462,17.325,Passenger,28.340,3.5,253.0,113.0,74.4,207.7,3.564,17.0,23.0,5/8/2012,101.329281
300M,Chrysler,30.696,NaN,Passenger,29.185,3.5,253.0,113.0,74.4,197.8,3.567,17.0,23.0,2/10/2012,101.655244
Concorde,Chrysler,31.148,13.725,Passenger,22.245,2.7,200.0,113.0,74.4,209.1,3.452,17.0,26.0,6/6/2012,80.023782
Sebring Conv.,Chrysler,32.775,14.180,Passenger,24.495,2.5,168.0,106.0,69.2,193.0,3.332,16.0,24.0,11/17/2011,69.521355
Sebring Coupe,Chrysler,7.854,12.360,Passenger,19.840,2.5,163.0,103.7,69.7,190.9,2.967,15.9,24.0,1/16/2012,65.957184
Cirrus,Chrysler,32.306,12.640,Passenger,16.480,2.0,132.0,108.0,71.0,186.0,2.911,16.0,27.0,10/6/2011,53.566200
Corvette,Chevrolet,17.947,36.225,Passenger,45.705,5.7,345.0,104.5,73.6,179.7,3.210,19.1,22.0,5/12/2012,141.141150
Camaro,Chevrolet,26.402,13.025,Passenger,24.340,3.8,200.0,101.1,74.1,193.2,3.500,16.8,25.0,10/23/2011,81.118543
Impala,Chevrolet,107.995,NaN,Passenger,18.890,3.4,180.0,110.5,73.0,200.0,3.389,17.0,27.0,6/18/2011,71.838039
Monte Carlo,Chevrolet,42.593,11.525,Passenger,19.390,3.4,180.0,110.5,72.7,197.9,3.340,17.0,27.0,12/22/2011,72.030917
Lumina,Chevrolet,24.629,10.310,Passenger,18.890,3.1,175.0,107.5,72.5,200.9,3.330,16.6,25.0,5/24/2011,69.991396
Malibu,Chevrolet,135.126,11.225,Passenger,16.535,3.1,170.0,107.0,69.4,190.4,3.051,15.0,25.0,3/19/2012,67.314462
Prizm,Chevrolet,32.299,9.125,Passenger,13.960,1.8,120.0,97.1,66.7,174.3,2.398,13.2,33.0,9/11/2011,48.297636
Cavalier,Chevrolet,145.519,9.250,Passenger,13.260,2.2,115.0,104.1,67.9,180.9,2.676,14.3,27.0,8/17/2011,46.363347
Metro,Chevrolet,21.855,5.160,Passenger,9.235,1.0,55.0,93.1,62.6,149.4,1.895,10.3,45.0,4/13/2012,23.276272
Escalade,Cadillac,14.785,NaN,Car,46.225,5.7,255.0,117.5,77.0,201.2,5.572,30.0,15.0,4/17/2012,109.509117
Eldorado,Cadillac,6.536,25.725,Passenger,39.665,4.6,275.0,108.0,75.5,200.6,3.843,19.0,22.0,11/27/2011,113.765874
DeVille,Cadillac,63.729,22.525,Passenger,39.895,4.6,275.0,115.3,74.5,207.2,3.978,18.5,22.0,2/23/2012,113.854598
Seville,Cadillac,15.943,27.100,Passenger,44.475,4.6,275.0,112.2,75.0,201.0,NaN,18.5,22.0,4/29/2011,115.621358
Catera,Cadillac,11.185,18.225,Passenger,31.010,3.0,200.0,107.4,70.3,194.8,3.770,18.0,22.0,9/28/2011,83.483094
Regal,Buick,39.350,13.740,Passenger,25.300,3.8,240.0,109.0,72.7,196.2,3.543,17.5,23.0,9/3/2011,95.636703
LeSabre,Buick,83.257,13.360,Passenger,27.885,3.8,205.0,112.2,73.5,200.0,3.591,17.5,25.0,7/23/2011,84.254526
Park Avenue,Buick,27.851,20.190,Passenger,31.965,3.8,205.0,113.8,74.7,206.8,3.778,18.5,24.0,3/23/2012,85.828408
Century,Buick,91.561,12.475,Passenger,21.975,3.1,175.0,109.0,72.7,194.6,3.368,17.5,25.0,11/2/2011,71.181451
328i,BMW,9.231,28.675,Passenger,33.400,2.8,193.0,107.3,68.5,176.0,3.197,16.6,24.0,1/29/2012,81.877069
528i,BMW,17.527,36.125,Passenger,38.900,2.8,193.0,111.4,70.9,188.0,3.472,18.5,25.0,4/4/2011,83.998724
323i,BMW,19.747,NaN,Passenger,26.990,2.5,170.0,107.3,68.4,176.0,3.179,16.6,26.0,6/28/2011,71.191207
A8,Audi,1.380,39.000,Passenger,62.000,4.2,310.0,113.0,74.0,198.2,3.902,23.7,21.0,2/27/2012,134.656858
A6,Audi,18.780,23.555,Passenger,33.950,2.8,200.0,108.7,76.1,192.0,3.561,18.5,22.0,8/9/2011,84.565105
A4,Audi,20.397,22.255,Passenger,23.990,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
TL,Acura,39.384,19.875,Passenger,28.400,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
CL,Acura,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
RL,Acura,8.588,29.725,Passenger,42.000,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
Integra,Acura,16.919,16.360,Passenger,21.500,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150

In [39]:
pd.set_option("display.max_rows",None)

In [40]:
df.sort_values(by=["Manufacturer","Vehicle_type","Horsepower","Price_in_thousands"],ascending=[False,True,False,True])

,Manufacturer,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
Model,,,,,,,,,,,,,,,
C70,Volvo,3.493,NaN,Passenger,45.500,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
S80,Volvo,18.969,NaN,Passenger,36.000,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655
S70,Volvo,15.245,NaN,Passenger,27.500,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
V70,Volvo,17.531,NaN,Passenger,28.800,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
S40,Volvo,16.957,NaN,Passenger,23.400,1.9,160.0,100.5,67.6,176.6,2.998,15.8,25.0,2/18/2011,66.113057
V40,Volvo,3.545,NaN,Passenger,24.400,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
Passat,Volkswagen,51.102,16.725,Passenger,21.200,1.8,150.0,106.4,68.5,184.1,3.043,16.4,27.0,10/30/2012,61.701381
Golf,Volkswagen,9.761,11.425,Passenger,14.900,2.0,115.0,98.9,68.3,163.3,2.767,14.5,26.0,1/24/2011,46.943877
Beetle,Volkswagen,49.463,NaN,Passenger,15.900,2.0,115.0,98.9,67.9,161.1,2.769,14.5,26.0,10/20/2011,47.329632
Jetta,Volkswagen,83.721,13.240,Passenger,16.700,2.0,115.0,98.9,68.3,172.3,2.853,14.5,26.0,8/27/2011,47.638237
GTI,Volkswagen,5.596,13.760,Passenger,17.500,2.0,115.0,98.9,68.3,163.3,2.762,14.6,26.0,4/1/2011,47.946841
Cabrio,Volkswagen,9.569,16.575,Passenger,19.990,2.0,115.0,97.4,66.7,160.4,3.079,13.7,26.0,5/31/2011,48.907372
Land Cruiser,Toyota,9.835,34.080,Car,51.728,4.7,230.0,112.2,76.4,192.5,5.115,25.4,15.0,9/25/2011,102.528984
Sienna,Toyota,65.119,NaN,Car,22.368,3.0,194.0,114.2,73.4,193.5,3.759,20.9,22.0,10/5/2012,78.027219
4Runner,Toyota,68.411,19.425,Car,22.288,2.7,150.0,105.3,66.5,183.3,3.440,18.5,23.0,3/7/2011,62.355577
Tacoma,Toyota,84.087,9.575,Car,11.528,2.4,142.0,103.3,66.5,178.7,2.580,15.1,23.0,8/1/2011,55.297117
RAV4,Toyota,25.106,13.325,Car,16.888,2.0,127.0,94.9,66.7,163.8,2.668,15.3,27.0,5/6/2011,51.955109
Avalon,Toyota,63.849,18.140,Passenger,25.545,3.0,210.0,107.1,71.7,191.9,3.417,18.5,26.0,8/31/2011,84.911898
Celica,Toyota,33.269,15.445,Passenger,16.875,1.8,140.0,102.4,68.3,170.5,2.425,14.5,31.0,12/29/2012,56.496030
Camry,Toyota,247.994,13.245,Passenger,17.518,2.2,133.0,105.2,70.1,188.5,2.998,18.5,27.0,2/10/2011,54.372420
Corolla,Toyota,142.535,10.025,Passenger,13.108,1.8,120.0,97.0,66.7,174.0,2.420,13.2,33.0,4/11/2011,47.968972
Forester,Subaru,33.028,NaN,Car,20.095,2.5,165.0,99.4,68.3,175.2,3.125,15.9,24.0,9/10/2012,66.762943
Outback,Subaru,47.107,NaN,Passenger,22.695,2.5,165.0,103.5,67.5,185.8,3.415,16.9,25.0,7/7/2011,67.765908
LS,Saturn,49.989,NaN,Passenger,15.010,2.2,137.0,106.5,69.0,190.4,2.910,13.1,28.0,12/4/2012,54.819728
LW,Saturn,8.472,NaN,Passenger,18.835,2.2,137.0,106.5,69.0,190.4,3.075,13.1,27.0,8/5/2011,56.295243
SW,Saturn,5.223,10.790,Passenger,14.290,1.9,124.0,102.4,66.4,176.9,2.452,12.1,31.0,1/15/2011,49.865774
SL,Saturn,80.620,9.200,Passenger,10.685,1.9,100.0,102.4,66.4,176.9,2.332,12.1,33.0,8/16/2012,39.986425
SC,Saturn,24.546,10.590,Passenger,12.535,1.9,100.0,102.4,66.4,180.0,2.367,12.1,33.0,3/16/2011,40.700072
3-Sep,Saab,12.115,NaN,Passenger,26.100,2.0,185.0,102.6,67.4,182.2,2.990,16.9,23.0,6/12/2011,76.023048
5-Sep,Saab,9.191,NaN,Passenger,33.120,2.3,170.0,106.4,70.6,189.2,3.280,18.5,23.0,11/9/2012,73.503778
Carrera Coupe,Porsche,1.280,60.625,Passenger,71.020,3.4,300.0,92.6,69.5,174.5,3.032,17.0,21.0,12/21/2012,134.390975
Carrera Cabrio,Porsche,1.866,67.550,Passenger,74.970,3.4,300.0,92.6,69.5,174.5,3.075,17.0,23.0,7/11/2011,135.914710
Boxter,Porsche,8.982,41.250,Passenger,41.430,2.7,217.0,95.2,70.1,171.0,2.778,17.0,22.0,2/19/2012,93.437331
Montana,Pontiac,39.572,NaN,Car,25.635,3.4,185.0,120.0,72.7,201.3,3.942,25.0,23.0,7/22/2012,76.208440
Bonneville,Pontiac,35.945,13.225,Passenger,23.755,3.8,205.0,112.2,72.6,202.5,3.590,17.5,24.0,5/18/2011,82.661356
Firebird,Pontiac,19.911,17.805,Passenger,25.310,3.8,200.0,101.1,74.5,193.4,3.492,16.8,25.0,6/16/2012,81.492726
Grand Prix,Pontiac,92.364,14.010,Passenger,21.665,3.8,195.0,110.5,72.7,196.5,3.396,18.0,25.0,10/15/2012,78.318168
Grand Am,Pontiac,131.097,10.290,Passenger,19.720,3.4,175.0,107.0,70.4,186.3,3.091,15.2,25.0,11/26/2012,70.389737
Sunfire,Pontiac,51.645,13.790,Passenger,21.610,2.4,150.0,104.1,68.4,181.9,2.906,15.0,27.0,1/25/2012,62.015870
Voyager,Plymouth,24.155,12.025,Car,18.850,2.4,150.0,113.3,76.8,186.3,3.528,20.0,24.0,4/24/2011,60.951185
Prowler,Plymouth,1.872,NaN,Passenger,43.000,3.5,253.0,113.3,76.3,165.4,2.850,12.0,21.0,6/27/2012,106.984456
Neon,Plymouth,32.734,7.750,Passenger,12.640,2.0,132.0,105.0,74.4,174.4,2.559,12.5,29.0,4/26/2011,52.084899
Breeze,Plymouth,5.240,9.800,Passenger,16.080,2.0,132.0,108.0,71.0,186.3,2.942,16.0,27.0,11/14/2011,53.411898
Bravada,Oldsmobile,20.017,19.925,Car,31.598,4.3,190.0,107.0,67.8,181.2,4.068,17.5,19.0,9/21/2011,80.511673
Silhouette,Oldsmobile,24.361,15.240,Car,25.345,3.4,185.0,120.0,72.2,201.4,3.948,25.0,22.0,6/25/2011,76.096570
Aurora,Oldsmobile,14.690,19.890,Passenger,36.229,4.0,250.0,113.8,74.4,205.4,3.967,18.5,22.0,2/18/2011,103.441693
Intrigue,Oldsmobile,38.554,NaN,Passenger,24.150,3.5,215.0,109.0,73.6,195.9,3.455,18.0,NaN,4/1/2011,86.272523
Cutlass,Oldsmobile,1.112,11.240,Passenger,18.145,3.1,150.0,107.0,69.4,192.0,3.102,15.2,25.0,5/31/2011,60.861612
Alero,Oldsmobile,80.255,NaN,Passenger,18.270,2.4,150.0,107.0,70.1,186.7,2.958,15.0,27.0,10/20/2009,60.727447
Frontier,Nissan,65.005,NaN,Car,17.890,3.3,170.0,116.1,66.5,196.1,3.217,19.4,18.0,8/27/2011,67.889271
Xterra,Nissan,54.158,NaN,Car,22.799,3.3,170.0,104.3,70.4,178.0,3.821,19.4,18.0,1/24/2011,69.782944
Quest,Nissan,27.308,15.380,Car,26.399,3.3,170.0,112.2,74.9,194.8,3.991,20.0,21.0,3/7/2011,71.171664
Pathfinder,Nissan,42.574,17.810,Car,29.299,3.3,170.0,106.3,71.7,182.6,3.947,21.0,19.0,9/25/2011,72.290355
Maxima,Nissan,79.853,15.125,Passenger,26.249,3.0,222.0,108.3,70.3,190.5,3.294,18.5,25.0,5/6/2011,89.427820
Altima,Nissan,88.094,11.295,Passenger,20.390,2.4,155.0,103.1,69.1,183.5,3.012,15.9,25.0,8/2/2011,63.313728
Sentra,Nissan,42.643,8.450,Passenger,13.499,1.8,126.0,99.8,67.3,177.5,2.593,13.2,30.0,8/31/2011,50.241978
Montero,Mitsubishi,11.337,19.125,Car,31.807,3.5,200.0,107.3,69.9,186.6,4.520,24.3,18.0,1/17/2012,83.920815
Montero Sport,Mitsubishi,39.348,13.880,Car,22.527,3.0,173.0,107.3,66.7,178.3,3.510,19.5,20.0,5/18/2012,70.660942
Diamante,Mitsubishi,5.711,16.575,Passenger,24.997,3.5,210.0,107.1,70.3,194.1,3.443,19.0,22.0,8/28/2012,84.830779
3000GT,Mitsubishi,0.110,20.940,Passenger,25.450,3.0,161.0,97.2,72.4,180.3,3.131,19.8,21.0,6/29/2012,67.544155
Eclipse,Mitsubishi,42.541,10.395,Passenger,19.047,2.4,154.0,100.8,68.9,175.4,2.910,15.9,24.0,11/24/2012,62.441962
Galant,Mitsubishi,55.616,10.595,Passenger,17.357,2.4,145.0,103.7,68.5,187.8,2.945,16.3,25.0,1/29/2012,58.606773
Mirage,Mitsubishi,26.232,8.325,Passenger,13.987,1.8,113.0,98.4,66.5,173.6,2.250,13.2,30.0,4/23/2012,45.832181
Mountaineer,Mercury,27.609,20.430,Car,27.560,4.0,210.0,111.6,70.2,190.1,3.876,21.0,18.0,2/13/2008,85.949744
Villager,Mercury,20.380,14.795,Car,22.510,3.3,170.0,112.2,74.9,194.7,3.944,20.0,21.0,10/20/2009,69.671461
Grand Marquis,Mercury,81.174,14.875,Passenger,22.605,4.6,200.0,114.7,78.2,212.0,3.958,19.0,21.0,7/24/2012,80.657696
Sable,Mercury,67.956,11.030,Passenger,19.035,3.0,153.0,108.5,73.0,199.7,3.379,16.0,24.0,9/22/2012,62.239967
Mystique,Mercury,14.351,8.800,Passenger,16.240,2.0,125.0,106.5,69.1,184.8,2.769,15.0,28.0,12/19/2012,50.997748
Cougar,Mercury,26.529,13.890,Passenger,16.540,2.0,125.0,106.4,69.6,185.0,2.892,16.0,30.0,2/23/2012,51.113474
M-Class,Mercedes-B,28.976,NaN,Car,35.300,3.2,215.0,111.0,72.2,180.6,4.387,19.0,20.0,2/10/2011,90.495532
SL-Class,Mercedes-B,3.311,58.600,Passenger,82.600,5.0,302.0,99.0,71.3,177.1,4.125,21.1,20.0,3/17/2011,139.982294
CL500,Mercedes-B,0.954,NaN,Passenger,85.500,5.0,302.0,113.6,73.1,196.6,4.115,23.2,20.0,4/11/2011,141.100985
S-Class,Mercedes-B,16.774,50.375,Passenger,69.700,4.3,275.0,121.5,73.1,203.1,4.133,23.2,21.0,6/13/2011,125.273876
E-Class,Mercedes-B,27.602,41.450,Passenger,49.900,3.2,221.0,111.5,70.8,189.4,3.823,21.1,25.0,7/12/2011,98.249737
CLK Coupe,Mercedes-B,11.592,NaN,Passenger,41.600,3.2,215.0,105.9,67.8,180.3,3.213,16.4,26.0,7/8/2011,92.925792
SLK,Mercedes-B,7.998,NaN,Passenger,38.900,2.3,190.0,94.5,67.5,157.9,3.055,15.9,26.0,1/16/2011,82.807362
C-Class,Mercedes-B,18.392,26.050,Passenger,31.750,2.3,185.0,105.9,67.7,177.4,3.250,16.4,26.0,4/24/2011,78.280731
SLK230,Mercedes-B,1.526,NaN,Passenger,41.000,2.3,185.0,94.5,67.5,157.3,2.975,14.0,27.0,8/6/2011,81.848969
Navigator,Lincoln,22.925,NaN,Car,42.660,5.4,300.0,119.0,79.9,204.8,5.393,30.0,15.0,12/23/2012,123.972047
Continental,Lincoln,13.798,20.525,Passenger,39.080,4.6,275.0,109.0,73.6,208.5,3.868,20.0,22.0,8/3/2012,113.540207
Town car,Lincoln,48.911,21.725,Passenger,43.330,4.6,215.0,117.7,78.2,215.3,4.121,19.0,21.0,6/4/2012,93.957917
LX470,Lexus,9.126,NaN,Car,60.105,4.7,230.0,112.2,76.4,192.5,5.401,25.4,15.0,10/30/2012,105.760458
RX300,Lexus,51.238,NaN,Car,34.605,3.0,220.0,103.0,71.5,180.1,3.900,17.2,21.0,1/4/2012,91.943802
GS400,Lexus,3.334,NaN,Passenger,46.305,4.0,300.0,110.2,70.9,189.2,3.693,19.8,21.0,11/28/2012,125.013357
LS400,Lexus,6.375,40.375,Passenger,54.005,4.0,290.0,112.2,72.0,196.7,3.890,22.5,22.0,3/29/2012,124.446716
GS300,Lexus,12.698,32.075,Passenger,37.805,3.0,225.0,110.2,70.9,189.2,3.638,19.8,23.0,5/10/2012,94.946698
ES300,Lexus,24.072,26.975,Passenger,31.505,3.0,210.0,105.1,70.5,190.2,3.373,18.5,23.0,7/9/2012,87.211001
Grand Cherokee,Jeep,157.040,18.810,Car,26.895,4.0,195.0,105.9,72.3,181.5,3.880,20.5,19.0,12/10/2011,80.387779
Cherokee,Jeep,80.556,13.775,Car,21.620,4.0,190.0,101.4,69.4,167.5,3.194,20.0,20.0,10/5/2012,76.584440
Wrangler,Jeep,55.557,13.475,Car,14.460,2.5,120.0,93.4,66.7,152.0,3.045,19.0,17.0,3/4/2012,48.672898
S-Type,Jaguar,15.467,NaN,Passenger,42.800,3.0,240.0,114.5,71.6,191.3,3.650,18.4,21.0,11/3/2012,102.178985
I30,Infiniti,23.713,19.690,Passenger,29.465,3.0,227.0,108.3,70.2,193.7,3.342,18.5,25.0,4/15/2012,92.436889
Sonata,Hyundai,29.450,8.910,Passenger,14.999,2.4,148.0,106.3,71.6,185.4,3.072,17.2,25.0,6/14/2012,58.758249
Elantra,Hyundai,66.692,7.825,Passenger,11.799,2.0,140.0,100.4,66.9,174.0,2.626,14.5,27.0,11/15/2011,54.590045
Accent,Hyundai,41.184,5.860,Passenger,9.699,1.5,92.0,96.1,65.7,166.7,2.240,11.9,31.0,9/10/2012,36.672284
Odyssey,Honda,76.029,19.490,Car,26.000,3.5,210.0,118.1,75.6,201.2,4.288,20.0,23.0,2/8/2012,85.217691
Passport,Honda,12.855,17.525,Car,26.600,3.2,205.0,106.4,70.4,178.2,3.857,21.1,19.0,10/9/2012,83.602501
CR-V,Honda,73.203,17.710,Car,20.550,2.0,146.0,103.2,68.9,177.6,3.219,15.3,24.0,3/21/2012,60.087967
Accord,Honda,230.902,13.210,Passenger,15.350,2.3,135.0,106.9,70.3,188.8,2.932,17.1,27.0,5/20/2012,54.269548
Civic,Honda,199.685,9.850,Passenger,12.885,1.6,106.0,103.2,67.1,175.1,2.339,11.9,32.0,10/21/2011,42.879097
Expedition,Ford,125.338,23.575,Car,36.135,4.6,240.0,119.0,78.7,204.6,4.808,26.0,16.0,9/14/2012,100.024802
F-Series,Ford,540.561,15.075,Car,26.935,4.6,220.0,138.5,79.1,224.5,4.241,25.1,18.0,8/16/2012,89.401935
Explorer,Ford,276.747,16.640,Car,31.930,4.0,210.0,111.6,70.2,190.7,3.876,21.0,19.0,4/25/2012,87.635496
Windstar,Ford,155.787,13.175,Car,21.410,3.0,150.0,120.7,76.6,200.9,3.761,26.0,21.0,2/25/2012,62.095048
Ranger,Ford,220.650,7.850,Car,12.050,2.5,119.0,117.5,69.4,200.7,3.086,20.0,23.0,1/14/2012,47.389531
Crown Victoria,Ford,63.403,14.210,Passenger,22.195,4.6,200.0,114.7,78.2,212.0,3.908,19.0,21.0,9/26/2011,80.499537
Mustang,Ford,113.369,12.760,Passenger,21.560,3.8,190.0,101.3,73.1,183.2,3.203,15.7,24.0,1/31/2012,76.509185
Contour,Ford,35.068,8.835,Passenger,17.035,2.5,170.0,106.5,69.1,184.6,2.769,15.0,25.0,8/20/2012,67.351011
Taurus,Ford,245.815,10.055,Passenger,17.885,3.0,155.0,108.5,73.0,197.6,3.368,16.0,24.0,12/20/2011,62.503740
Escort,Ford,70.227,7.425,Passenger,12.070,2.0,110.0,98.4,67.0,174.7,2.468,12.7,30.0,3/31/2012,44.083709
Focus,Ford,175.670,NaN,Passenger,12.315,2.0,107.0,103.0,66.9,174.8,2.564,13.2,30.0,7/22/2012,43.117132
Ram Pickup,Dodge,227.061,15.060,Car,19.460,5.2,230.0,138.7,79.3,224.2,4.470,26.0,17.0,3/6/2012,90.211700
Durango,Dodge,101.323,NaN,Car,26.310,5.2,230.0,115.7,71.7,193.5,4.394,25.0,17.0,6/27/2012,92.854125
Ram Van,Dodge,31.038,13.425,Car,18.575,3.9,175.0,127.2,78.8,208.5,4.298,32.0,16.0,7/26/2012,70.078322
Ram Wagon,Dodge,16.767,15.510,Car,21.315,3.9,175.0,109.6,78.8,192.6,4.245,32.0,15.0,1/6/2012,71.135292
Caravan,Dodge,181.749,12.025,Car,19.565,2.4,150.0,113.3,76.8,186.3,3.533,20.0,24.0,9/1/2011,61.227000
Dakota,Dodge,111.313,11.260,Car,16.980,2.5,120.0,131.0,71.5,215.0,3.557,22.0,19.0,11/25/2011,49.645002
Viper,Dodge,0.916,58.470,Passenger,69.725,8.0,450.0,96.2,75.7,176.7,3.375,19.0,16.0,8/7/2011,188.144323
Intrepid,Dodge,88.028,12.275,Passenger,22.505,2.7,202.0,113.0,74.7,203.7,3.489,17.0,NaN,6/2/2012,80.831470
Stratus,Dodge,71.186,10.185,Passenger,20.230,2.5,168.0,108.0,71.0,186.0,3.058,16.0,24.0,10/31/2011,67.876108
Avenger,Dodge,4.734,12.545,Passenger,19.045,2.5,163.0,103.7,69.1,190.2,2.879,15.9,24.0,7/1/2012,65.650508
Neon,Dodge,76.034,7.750,Passenger,12.640,2.0,132.0,105.0,74.4,174.4,2.567,12.5,29.0,12/12/2011,52.084899
Town & Country,Chrysler,53.480,19.540,Car,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7/13/2011,NaN
LHS,Chrysler,13.462,17.325,Passenger,28.340,3.5,253.0,113.0,74.4,207.7,3.564,17.0,23.0,5/8/2012,101.329281
300M,Chrysler,30.696,NaN,Passenger,29.185,3.5,253.0,113.0,74.4,197.8,3.567,17.0,23.0,2/10/2012,101.655244
Concorde,Chrysler,31.148,13.725,Passenger,22.245,2.7,200.0,113.0,74.4,209.1,3.452,17.0,26.0,6/6/2012,80.023782
Sebring Conv.,Chrysler,32.775,14.180,Passenger,24.495,2.5,168.0,106.0,69.2,193.0,3.332,16.0,24.0,11/17/2011,69.521355
Sebring Coupe,Chrysler,7.854,12.360,Passenger,19.840,2.5,163.0,103.7,69.7,190.9,2.967,15.9,24.0,1/16/2012,65.957184
Cirrus,Chrysler,32.306,12.640,Passenger,16.480,2.0,132.0,108.0,71.0,186.0,2.911,16.0,27.0,10/6/2011,53.566200
Corvette,Chevrolet,17.947,36.225,Passenger,45.705,5.7,345.0,104.5,73.6,179.7,3.210,19.1,22.0,5/12/2012,141.141150
Camaro,Chevrolet,26.402,13.025,Passenger,24.340,3.8,200.0,101.1,74.1,193.2,3.500,16.8,25.0,10/23/2011,81.118543
Impala,Chevrolet,107.995,NaN,Passenger,18.890,3.4,180.0,110.5,73.0,200.0,3.389,17.0,27.0,6/18/2011,71.838039
Monte Carlo,Chevrolet,42.593,11.525,Passenger,19.390,3.4,180.0,110.5,72.7,197.9,3.340,17.0,27.0,12/22/2011,72.030917
Lumina,Chevrolet,24.629,10.310,Passenger,18.890,3.1,175.0,107.5,72.5,200.9,3.330,16.6,25.0,5/24/2011,69.991396
Malibu,Chevrolet,135.126,11.225,Passenger,16.535,3.1,170.0,107.0,69.4,190.4,3.051,15.0,25.0,3/19/2012,67.314462
Prizm,Chevrolet,32.299,9.125,Passenger,13.960,1.8,120.0,97.1,66.7,174.3,2.398,13.2,33.0,9/11/2011,48.297636
Cavalier,Chevrolet,145.519,9.250,Passenger,13.260,2.2,115.0,104.1,67.9,180.9,2.676,14.3,27.0,8/17/2011,46.363347
Metro,Chevrolet,21.855,5.160,Passenger,9.235,1.0,55.0,93.1,62.6,149.4,1.895,10.3,45.0,4/13/2012,23.276272
Escalade,Cadillac,14.785,NaN,Car,46.225,5.7,255.0,117.5,77.0,201.2,5.572,30.0,15.0,4/17/2012,109.509117
Eldorado,Cadillac,6.536,25.725,Passenger,39.665,4.6,275.0,108.0,75.5,200.6,3.843,19.0,22.0,11/27/2011,113.765874
DeVille,Cadillac,63.729,22.525,Passenger,39.895,4.6,275.0,115.3,74.5,207.2,3.978,18.5,22.0,2/23/2012,113.854598
Seville,Cadillac,15.943,27.100,Passenger,44.475,4.6,275.0,112.2,75.0,201.0,NaN,18.5,22.0,4/29/2011,115.621358
Catera,Cadillac,11.185,18.225,Passenger,31.010,3.0,200.0,107.4,70.3,194.8,3.770,18.0,22.0,9/28/2011,83.483094
Regal,Buick,39.350,13.740,Passenger,25.300,3.8,240.0,109.0,72.7,196.2,3.543,17.5,23.0,9/3/2011,95.636703
LeSabre,Buick,83.257,13.360,Passenger,27.885,3.8,205.0,112.2,73.5,200.0,3.591,17.5,25.0,7/23/2011,84.254526
Park Avenue,Buick,27.851,20.190,Passenger,31.965,3.8,205.0,113.8,74.7,206.8,3.778,18.5,24.0,3/23/2012,85.828408
Century,Buick,91.561,12.475,Passenger,21.975,3.1,175.0,109.0,72.7,194.6,3.368,17.5,25.0,11/2/2011,71.181451
328i,BMW,9.231,28.675,Passenger,33.400,2.8,193.0,107.3,68.5,176.0,3.197,16.6,24.0,1/29/2012,81.877069
528i,BMW,17.527,36.125,Passenger,38.900,2.8,193.0,111.4,70.9,188.0,3.472,18.5,25.0,4/4/2011,83.998724
323i,BMW,19.747,NaN,Passenger,26.990,2.5,170.0,107.3,68.4,176.0,3.179,16.6,26.0,6/28/2011,71.191207
A8,Audi,1.380,39.000,Passenger,62.000,4.2,310.0,113.0,74.0,198.2,3.902,23.7,21.0,2/27/2012,134.656858
A6,Audi,18.780,23.555,Passenger,33.950,2.8,200.0,108.7,76.1,192.0,3.561,18.5,22.0,8/9/2011,84.565105
A4,Audi,20.397,22.255,Passenger,23.990,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
TL,Acura,39.384,19.875,Passenger,28.400,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
CL,Acura,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
RL,Acura,8.588,29.725,Passenger,42.000,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
Integra,Acura,16.919,16.360,Passenger,21.500,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150

In [41]:
df.sort_values(by=["Manufacturer","Vehicle_type","Horsepower","Price_in_thousands"],ascending=[False,True,False,True]).loc[:,["Manufacturer","Vehicle_type","Horsepower","Price_in_thousands"]]

               Manufacturer Vehicle_type  Horsepower  Price_in_thousands
Model
C70                   Volvo    Passenger       236.0              45.500
S80                   Volvo    Passenger       201.0              36.000
S70                   Volvo    Passenger       168.0              27.500
V70                   Volvo    Passenger       168.0              28.800
S40                   Volvo    Passenger       160.0              23.400
V40                   Volvo    Passenger       160.0              24.400
Passat           Volkswagen    Passenger       150.0              21.200
Golf             Volkswagen    Passenger       115.0              14.900
Beetle           Volkswagen    Passenger       115.0              15.900
Jetta            Volkswagen    Passenger       115.0              16.700
GTI              Volkswagen    Passenger       115.0              17.500
Cabrio           Volkswagen    Passenger       115.0              19.990
Land Cruiser         Toyota          Car       230.0              51.728
Sienna               Toyota          Car       194.0              22.368
4Runner              Toyota          Car       150.0              22.288
Tacoma               Toyota          Car       142.0              11.528
RAV4                 Toyota          Car       127.0              16.888
Avalon               Toyota    Passenger       210.0              25.545
Celica               Toyota    Passenger       140.0              16.875
Camry                Toyota    Passenger       133.0              17.518
Corolla              Toyota    Passenger       120.0              13.108
Forester             Subaru          Car       165.0              20.095
Outback              Subaru    Passenger       165.0              22.695
LS                   Saturn    Passenger       137.0              15.010
LW                   Saturn    Passenger       137.0              18.835
SW                   Saturn    Passenger       124.0              14.290
SL                   Saturn    Passenger       100.0              10.685
SC                   Saturn    Passenger       100.0              12.535
3-Sep                  Saab    Passenger       185.0              26.100
5-Sep                  Saab    Passenger       170.0              33.120
Carrera Coupe       Porsche    Passenger       300.0              71.020
Carrera Cabrio      Porsche    Passenger       300.0              74.970
Boxter              Porsche    Passenger       217.0              41.430
Montana             Pontiac          Car       185.0              25.635
Bonneville          Pontiac    Passenger       205.0              23.755
Firebird            Pontiac    Passenger       200.0              25.310
Grand Prix          Pontiac    Passenger       195.0              21.665
Grand Am            Pontiac    Passenger       175.0              19.720
Sunfire             Pontiac    Passenger       150.0              21.610
Voyager            Plymouth          Car       150.0              18.850
Prowler            Plymouth    Passenger       253.0              43.000
Neon               Plymouth    Passenger       132.0              12.640
Breeze             Plymouth    Passenger       132.0              16.080
Bravada          Oldsmobile          Car       190.0              31.598
Silhouette       Oldsmobile          Car       185.0              25.345
Aurora           Oldsmobile    Passenger       250.0              36.229
Intrigue         Oldsmobile    Passenger       215.0              24.150
Cutlass          Oldsmobile    Passenger       150.0              18.145
Alero            Oldsmobile    Passenger       150.0              18.270
Frontier             Nissan          Car       170.0              17.890
Xterra               Nissan          Car       170.0              22.799
Quest                Nissan          Car       170.0              26.399
Pathfinder           Nissan          Car       170.0              29.299
Maxima               Nissan    Passenger       222.0              26.249
Altima               Nissan    Passenger       155.0              20.390
Sentra               Nissan    Passenger       126.0              13.499
Montero          Mitsubishi          Car       200.0              31.807
Montero Sport    Mitsubishi          Car       173.0              22.527
Diamante         Mitsubishi    Passenger       210.0              24.997
3000GT           Mitsubishi    Passenger       161.0              25.450
Eclipse          Mitsubishi    Passenger       154.0              19.047
Galant           Mitsubishi    Passenger       145.0              17.357
Mirage           Mitsubishi    Passenger       113.0              13.987
Mountaineer         Mercury          Car       210.0              27.560
Villager            Mercury          Car       170.0              22.510
Grand Marquis       Mercury    Passenger       200.0              22.605
Sable               Mercury    Passenger       153.0              19.035
Mystique            Mercury    Passenger       125.0              16.240
Cougar              Mercury    Passenger       125.0              16.540
M-Class          Mercedes-B          Car       215.0              35.300
SL-Class         Mercedes-B    Passenger       302.0              82.600
CL500            Mercedes-B    Passenger       302.0              85.500
S-Class          Mercedes-B    Passenger       275.0              69.700
E-Class          Mercedes-B    Passenger       221.0              49.900
CLK Coupe        Mercedes-B    Passenger       215.0              41.600
SLK              Mercedes-B    Passenger       190.0              38.900
C-Class          Mercedes-B    Passenger       185.0              31.750
SLK230           Mercedes-B    Passenger       185.0              41.000
Navigator           Lincoln          Car       300.0              42.660
Continental         Lincoln    Passenger       275.0              39.080
Town car            Lincoln    Passenger       215.0              43.330
LX470                 Lexus          Car       230.0              60.105
RX300                 Lexus          Car       220.0              34.605
GS400                 Lexus    Passenger       300.0              46.305
LS400                 Lexus    Passenger       290.0              54.005
GS300                 Lexus    Passenger       225.0              37.805
ES300                 Lexus    Passenger       210.0              31.505
Grand Cherokee         Jeep          Car       195.0              26.895
Cherokee               Jeep          Car       190.0              21.620
Wrangler               Jeep          Car       120.0              14.460
S-Type               Jaguar    Passenger       240.0              42.800
I30                Infiniti    Passenger       227.0              29.465
Sonata              Hyundai    Passenger       148.0              14.999
Elantra             Hyundai    Passenger       140.0              11.799
Accent              Hyundai    Passenger        92.0               9.699
Odyssey               Honda          Car       210.0              26.000
Passport              Honda          Car       205.0              26.600
CR-V                  Honda          Car       146.0              20.550
Accord                Honda    Passenger       135.0              15.350
Civic                 Honda    Passenger       106.0              12.885
Expedition             Ford          Car       240.0              36.135
F-Series               Ford          Car       220.0              26.935
Explorer               Ford          Car       210.0              31.930
Windstar               Ford          Car       150.0              21.410
Ranger                 Ford          Car       119.0              12.050
Crown Victoria         Ford    Passenger       200.0              22.195
Mustang                Ford    Passenger       190.0              21.560
Contour                Ford    Passenger       170.0              17.035
Taurus                 Ford    Passenger       155.0              17.885
Escort                 Ford    Passenger       110.0              12.070
Focus                  Ford    Passenger       107.0              12.315
Ram Pickup            Dodge          Car       230.0              19.460
Durango               Dodge          Car       230.0              26.310
Ram Van               Dodge          Car       175.0              18.575
Ram Wagon             Dodge          Car       175.0              21.315
Caravan               Dodge          Car       150.0              19.565
Dakota                Dodge          Car       120.0              16.980
Viper                 Dodge    Passenger       450.0              69.725
Intrepid              Dodge    Passenger       202.0              22.505
Stratus               Dodge    Passenger       168.0              20.230
Avenger               Dodge    Passenger       163.0              19.045
Neon                  Dodge    Passenger       132.0              12.640
Town & Country     Chrysler          Car         NaN                 NaN
LHS                Chrysler    Passenger       253.0              28.340
300M               Chrysler    Passenger       253.0              29.185
Concorde           Chrysler    Passenger       200.0              22.245
Sebring Conv.      Chrysler    Passenger       168.0              24.495
Sebring Coupe      Chrysler    Passenger       163.0              19.840
Cirrus             Chrysler    Passenger       132.0              16.480
Corvette          Chevrolet    Passenger       345.0              45.705
Camaro            Chevrolet    Passenger       200.0              24.340
Impala            Chevrolet    Passenger       180.0              18.890
Monte Carlo       Chevrolet    Passenger       180.0              19.390
Lumina            Chevrolet    Passenger       175.0              18.890
Malibu            Chevrolet    Passenger       170.0              16.535
Prizm             Chevrolet    Passenger       120.0              13.960
Cavalier          Chevrolet    Passenger       115.0              13.260
Metro             Chevrolet    Passenger        55.0               9.235
Escalade           Cadillac          Car       255.0              46.225
Eldorado           Cadillac    Passenger       275.0              39.665
DeVille            Cadillac    Passenger       275.0              39.895
Seville            Cadillac    Passenger       275.0              44.475
Catera             Cadillac    Passenger       200.0              31.010
Regal                 Buick    Passenger       240.0              25.300
LeSabre               Buick    Passenger       205.0              27.885
Park Avenue           Buick    Passenger       205.0              31.965
Century               Buick    Passenger       175.0              21.975
328i                    BMW    Passenger       193.0              33.400
528i                    BMW    Passenger       193.0              38.900
323i                    BMW    Passenger       170.0              26.990
A8                     Audi    Passenger       310.0              62.000
A6                     Audi    Passenger       200.0              33.950
A4                     Audi    Passenger       150.0              23.990
TL                    Acura    Passenger       225.0              28.400
CL                    Acura    Passenger       225.0                 NaN
RL                    Acura    Passenger       210.0              42.000
Integra               Acura    Passenger       140.0              21.500

In [42]:
df.groupby("Manufacturer")

In [43]:
df.groupby("Manufacturer")["Sales_in_thousands"]

In [44]:
df.groupby("Manufacturer")["Sales_in_thousands"].mean()

Manufacturer
Acura          19.751250
Audi           13.519000
BMW            15.501667
Buick          60.504750
Cadillac       22.435600
Chevrolet      61.596111
Chrysler       28.817286
Dodge          82.740818
Ford          183.875909
Honda         118.534800
Hyundai        45.775333
Infiniti       23.713000
Jaguar         15.467000
Jeep           97.717667
Lexus          17.807167
Lincoln        28.544667
Mercedes-B     13.013889
Mercury        39.666500
Mitsubishi     25.842143
Nissan         57.090714
Oldsmobile     29.831500
Plymouth       16.000250
Pontiac        61.755667
Porsche         4.042667
Saab           10.653000
Saturn         33.770000
Subaru         40.067500
Toyota         82.245000
Volkswagen     34.868667
Volvo          12.623333
Name: Sales_in_thousands, dtype: float64

In [45]:
df.groupby("Manufacturer")["Sales_in_thousands"].sum()

Manufacturer
Acura           79.005
Audi            40.557
BMW             46.505
Buick          242.019
Cadillac       112.178
Chevrolet      554.365
Chrysler       201.721
Dodge          910.149
Ford          2022.635
Honda          592.674
Hyundai        137.326
Infiniti        23.713
Jaguar          15.467
Jeep           293.153
Lexus          106.843
Lincoln         85.634
Mercedes-B     117.125
Mercury        237.999
Mitsubishi     180.895
Nissan         399.635
Oldsmobile     178.989
Plymouth        64.001
Pontiac        370.534
Porsche         12.128
Saab            21.306
Saturn         168.850
Subaru          80.135
Toyota         740.205
Volkswagen     209.212
Volvo           75.740
Name: Sales_in_thousands, dtype: float64

In [47]:
df.head()

,Manufacturer,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
Model,,,,,,,,,,,,,,,
Integra,Acura,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
TL,Acura,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
CL,Acura,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
RL,Acura,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
A4,Audi,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639

In [46]:
df[df["Vehicle_type"]=="Passenger"].groupby("Manufacturer")["Engine_size"].min()

Manufacturer
Acura         1.8
Audi          1.8
BMW           2.5
Buick         3.1
Cadillac      3.0
Chevrolet     1.0
Chrysler      2.0
Dodge         2.0
Ford          2.0
Honda         1.6
Hyundai       1.5
Infiniti      3.0
Jaguar        3.0
Lexus         3.0
Lincoln       4.6
Mercedes-B    2.3
Mercury       2.0
Mitsubishi    1.8
Nissan        1.8
Oldsmobile    2.4
Plymouth      2.0
Pontiac       2.4
Porsche       2.7
Saab          2.0
Saturn        1.9
Subaru        2.5
Toyota        1.8
Volkswagen    1.8
Volvo         1.9
Name: Engine_size, dtype: float64